### ISSUE TITLE
Incorporate the Dockerfile and nginx changes from PR #1234

### ISSUE THREAD

**Issue by morgantaschuk** [miso-lims/miso-lims#1241]
.@crashfrog opened a pull request with changes to the Dockerfile and repository here: https://github.com/TGAC/miso-lims/pull/1231 Unfortunately we can't pull these into develop as they are right now because of merge conflicts. Some required tests are disabled and dependencies are removed (interop). We'll have to cherry pick them on to develop.

This issue is to pull out the changes they made:
- Use the changes from the Dockerfile and docker-compose.yml
- add in nginx configuration
- add the notes into the readme about the Dockerfile
- use .env file to configure the base URL and the location of the DB

**Comment by djcooke** [comment]
Closing issue as we've made similar changes and now have docker-compose options and documentation for configuring them for both demo and production use
