### ISSUE TITLE
Feature Request: Text/Notes: Hyperlinks should be recognized

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#1260]
When creating a note or adding a description it would be nice to have hyperlinks being clickable by user.
Currently hyperlinks are presented as plain text.

Background: We are keeping BA images or any other (external) documentation of samples/tissue/whatever on a separate server and provide hyperlinks in MISO for easy access. 

Version: v0.2.101

**Comment by djcooke** [comment]
This isn't really doable for descriptions as they are editable in-place, and I don't think that changing that makes sense. It could work for notes though
