### ISSUE TITLE
"Errors" in Run Metrics Table

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#1483]
What is the "Errors (Read/Index 1/2)" etc expressing? I do see numbers above 90. That's not %, and no absolute numbers.

![image](https://user-images.githubusercontent.com/1837422/40900414-ba30a84a-67cb-11e8-8f15-f0af453303e9.png)

These numbers do not make sense (to me) ... this is a midoutput PE75 NextSeq500 run..

**Comment by apmasell** [comment]
These numbers from from the Illumina interop package, so we copied the output from the programs that displayed summaries in that. The errors should be “% > Q30” for each individual lane (where the first “% > Q30” column is the one for the summary across all the reads. The same is true for the “Aligned” columns. I'm happy to rename things; we just copied what the existing summary tools were doing and don't really understand what is going on because the documentation is so poor.

**Comment by sklages** [comment]
The "%>=Q30" is the fraction of bases with a quality value of at least 30 for a given read. 

The error columns should show error rates (in %) for a given sequencing read. These error rates are calculated from the PhiX alignments (which in turn is displayed in column "Aligned"). Illumina InterOp package should provide the error rates. No error rates can be calculated if a) there is no PhiX loaded and b) if the read is shorter than 25 cycles. So you won't ever see any error rates for index reads.
These error rates are important to get an idea of sequencing/device performance independently from the loaded libraries (which could be "bad").

So "Errors Read1/2" should be named "Error Rate R1 %" (R2) and should display fractions, e.g. "2.3". 
As there are hardly index reads beyond 25 cycles it is not really necessary to display error rates for these reads as these are usually 0 (zero).

Maybe just another little thing: 

   * "Density" and "Density PF" should be integer values, the same for the stddev.
   * it is probably correct but not necessary to display stddev for error and align rates, but if displayed it should suffice to use one or two digits.
   * it would be nice to see "Yield" (sum R1+R2, integer) and "Cluster PF" in the table
   * as "Densities" are nicely plotted just below the table, it is not necessary to display all three "Density" values in the table, maybe "Density" suffice. 
   * instead you could display the values for "Phasing" and "Prephasing" as these do not show up anywhere in MISO run stats. (SLOPE/OFFSET). But this may take to much space in current table layout.

just some thoughts :-)

**Comment by apmasell** [comment]
We've recently added the cluster PF changes already. I'm not clear on a lot of the changes you're suggesting. The renames and fraction changes are easy, so I'll start there.

**Comment by slazicoicr** [comment]
### Regarding Error Columns
The Interop line populating those values is https://github.com/TGAC/miso-lims/blob/c29733328179e85cb11bf9ed58640078a83ad1c7/runscanner-illumina/main.cpp#L358-L359

Each Error column represents the q30 value for that read and I am at a loss for words why the Interop line uses the word "Error" for them. Even stranger, the q30 column and Error (Read 1) are always the same values.

My suggestion would be to remove the q30 column and rename the Error columns to q30 (Read 1), q30 (Read 2), etc.

### Regarding Density Integer
The unit for Cluster Density is K clusters/mm<sup>2</sup>, which explains the occurrence of the rational numbers. From the screenshot above, 192.5 &#xb1; 7.683 K clusters/mm<sup>2</sup> is an integer value when expanded to 192500 &#xb1; 7683 clusters/mm<sup>2</sup>.

### Regarding Removing Columns
That should be a wider discussion, as I am not sure who depends on them

**Comment by djcooke** [comment]
I've made the changes suggested by @slazicoicr in https://github.com/miso-lims/runscanner/pull/60

**Comment by djcooke** [comment]
@sklages I think there have been a few changes to the metrics since you opened this issue. Are there any related problems remaining in recent MISO versions?

**Comment by sklages** [comment]
@djcooke - nope. Seems to be fine now :-) Thanks.
