### ISSUE TITLE
doc not consistant, beginner lost

### ISSUE THREAD

**Issue by ray1919** [miso-lims/miso-lims#1924]
I follow the git readme instructions like 
```
wget https://github.com/miso-lims/miso-lims/archive/master.zip
unzip master.zip 'miso-lims-master/.docker/*'
mv miso-lims-master/.docker miso-lims-compose
rm -r master.zip miso-lims-master/
cd miso-lims-compose
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password && MISO_TAG=latest
echo "changeme" > ./.miso_db_password
docker-compose -f demo.detailed.yml up
```

However, there is no `demo.plain.yml` in the .docker dir in master.zip, but `git clone` the repo does have `demo.plain.yml` in the .docker dir. Even though `docker-compose -f demo.detailed.yml up` does make error in this directory.

Then I found [installation guide](https://miso-lims.github.io/miso-lims/adm/installation-guide.html), and using `sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.detailed.yml up` to run the demo.

Then the server started, but the guild have not tell me where to login, I check some old issues in the git page, and open the interface in localhost:8090.

Then I do not know the username and password. finally I made it by guess admin/admin.

**As the installation guide, I have not do any 1-5 step, and server could start, how does these matters?**

> Installing MISO in production using compose
> The docker-compose.prod.yml file is an example for how to create a compose file to be used in production. We suggest the following:
> 
> 1. Mount the MySQL database to a permanent, backed-up location using the instructions in MySQL Docker Hub.
> 
> 2. Mount the MISO files storage location to a permanent, backed up location
> 
> 3. Omit or modify the docker-compose.override.yml file to pre-load desired data (if any). Starting MISO with an entirely empty database will not provide full functions: see the administrator’s manual for more information on stored procedures or setup, or the demo data under .docker/detailed_sample_config.
> 
> 4. Modify and mount the miso.properties file to have your desired configuration.
> 
> 5. Change the username and password for the database using the environmental variables

**How could I login into the mysql db using mysql client, I tried `mysql -u tgaclims -p -P 3307` but it failed**

I think there must be something wrong. I was new to docker. **Would you tell which installation guide should I follow?**

**Comment by djcooke** [comment]
Hello,

Sorry for the confusion. We have actually just reorganized our Docker compose files and the new ones have not been officially released yet. Our main branch on GitHub is the `develop` branch, which is ahead of `master`. The `master` branch is always set to our latest official release. This means you were reading documentation (the readme) from `develop`, which spoke of changes that had not yet been made in `master`, but you were downloading the files from `master`.

The docker compose changes will be in release 0.2.176, which should be made official next Tuseday, May 14. I wouldn't recommend using the old compose files at this point, so you could either wait until Tuesday to use the 0.2.176 release after it's made official, or you can use it early by replacing the first four lines of the script you pasted above with this:

```
wget https://github.com/miso-lims/miso-lims/archive/v0.2.176.zip
unzip v0.2.176.zip 'miso-lims-0.2.176/.docker/*'
mv miso-lims-0.2.176/.docker miso-lims-compose
rm -r v0.2.176.zip miso-lims-master/
```

You can then follow the instructions in the readme here for the MISO demo: https://github.com/miso-lims/miso-lims/blob/v0.2.176/readme.md

The documentation for setting up MISO for production using Docker compose is here: https://github.com/miso-lims/miso-lims/blob/develop/docs/_posts/2019-05-01-compose-installation-guide.md

Note that these are direct links to the documentation for version 0.2.176 and some links within may be broken until the release is official. Please let us know if you have any more trouble.

**Comment by ray1919** [comment]
Thank you.

**Comment by ray1919** [comment]
There is typo in [https://github.com/miso-lims/miso-lims/blob/develop/docs/_posts/2019-05-01-compose-installation-guide.md](https://github.com/miso-lims/miso-lims/blob/develop/docs/_posts/2019-05-01-compose-installation-guide.md#adding-persistent-storage)

`export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password && MISO_TAG=latest`

The last var(MISO_TAG) has no `export`

**Comment by djcooke** [comment]
Fixed typo in PR https://github.com/miso-lims/miso-lims/pull/1925. Thanks for pointing it out
