### ISSUE TITLE
ERROR: no such image: misolims/miso-lims-migration:: invalid reference format

### ISSUE THREAD

**Issue by AKWB** [miso-lims/miso-lims#1976]
Hi there,

I am not a docker specialist (yet). I followed the instructions:
wget https://github.com/miso-lims/miso-lims/archive/master.zip
unzip master.zip 'miso-lims-master/.docker/*'
mv miso-lims-master/.docker miso-lims-compose
rm -r master.zip miso-lims-master/
cd miso-lims-compose
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password && MISO_TAG=latest
echo "changeme" > ./.miso_db_password
docker-compose -f demo.plain.yml up

However it ends with:
WARNING: The MISO_TAG variable is not set. Defaulting to a blank string.
Creating network "miso-lims-compose_default" with the default driver
Pulling db (mysql:5.7.25)...
5.7.25: Pulling from library/mysql
27833a3ba0a5: Pull complete
864c283b3c4b: Pull complete
cea281b2278b: Pull complete
8f856c14f5af: Pull complete
9c4f38c23b6f: Pull complete
1b810e1751b3: Pull complete
5479aaef3d30: Pull complete
1d924ec3d520: Pull complete
1ab7ae63ac60: Pull complete
08aa5f3680e9: Pull complete
a832d0a0972a: Pull complete
Digest: sha256:dba5fed182e64064b688ccd22b2f9cad4ee88608c82f8cff21e17bab8da72b81
Status: Downloaded newer image for mysql:5.7.25
ERROR: no such image: misolims/miso-lims-migration:: invalid reference format

Any suggestion?

**Comment by djcooke** [comment]
Looks like an error in our instructions. The `MISO_TAG` variable should be exported along with the rest. Replace the export line with this:

```
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password && export MISO_TAG=latest
```

**Comment by AKWB** [comment]
seems to work...

Now I have a warning:
flyway_1  | WARNING: DB: Unknown table 'lims.CompletedPartitions' (SQL State: 42S02 - Error Code: 1051)
miso-lims-compose_flyway_1 exited with code 0

I can open http://localhost/miso, login with admin/admin and get:
HTTP Status 404 – Not Found
Type Status Report
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.38

**Comment by AKWB** [comment]
If I go on "backwards" its going to http://localhost/miso/mainMenu
this works...looks like...

**Comment by djcooke** [comment]
The Flyway warnings come from MySQL and are not a problem. Exiting with code 0 is good.

`http://localhost/miso` is not the correct URL, but we should add a redirect from that to the `mainMenu` page to prevent confusion. `http://localhost` is the URL we should point you to in the docs.

I'll fix the docs and add the redirect. Thanks for reporting this, and please let us know if you have any other issues

**Comment by djcooke** [comment]
Fixed docs and added redirect in https://github.com/miso-lims/miso-lims/pull/1979
