### ISSUE TITLE
Metrics not showing after setting "Sequencing Parameters" manually

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#1984]
In some cases `Sequencing Parameters` (Illumina) cannot be set automatically by MISO (for whatever reasons). In those cases I use the dropdown menu and set the parameters as required.

Before setting `Sequencing Parameters` I do see metrics graphics just as expected. After setting `Sequencing Parameters` via drop-down menu and saving the run, the metrics are vanished :-(

```
Sequencing Parameters:* -> not selected, Metrics OK
Sequencing Parameters:* -> SELECT some parameters, Metrics "No graphs available".
```
Any idea?

**Comment by djcooke** [comment]
Thanks for reporting this. Metrics are being lost whenever a run is saved on the Edit Run page. This bug has likely existed since v0.2.176 when the Edit Run page was updated.

**Comment by djcooke** [comment]
Fixed here: https://github.com/miso-lims/miso-lims/pull/1985

I just prepared release v0.2.180 yesterday, but will likely skip turning that into an official release and prepare v0.2.181 later today

**Comment by djcooke** [comment]
I should note that the metrics are actually being deleted from the database. Restarting Run Scanner or MISO should cause them to be repopulated though

**Comment by djcooke** [comment]
Had the wrong numbers above - v0.2.182 is the latest version, and includes the fix. We are now running it in production at OICR, and it is scheduled for official release July 4.
