### ISSUE TITLE
starting up with docker-compose, problems with flyway

### ISSUE THREAD

**Issue by Inkimar** [miso-lims/miso-lims#1987]
Hello,

I am trying out miso, starting up all the services - the flyway service does not start.
Still I am able to go to localhost and log in.
sending the error log from docker-compose.log.

regards, i
[flyway.log](https://github.com/miso-lims/miso-lims/files/3318454/flyway.log)

**Comment by djcooke** [comment]
The attached log shows Flyway running successfully - exiting with code 0 is good. Flyway only runs during start-up to ensure that your database schema is up to date, and then it exits
