### ISSUE TITLE
The creation of user account doesn't work, keep saying wrong password

### ISSUE THREAD

**Issue by alarawms** [miso-lims/miso-lims#2054]
The creation of user account fails due to wrong unmatched password. 
while the password is correct.

**Comment by kullrich** [comment]
Hi, same issue for me. It seems to be related to the following mismatch of the "Password" div and the "Confirm Password" div.

If I change e.g the Confirm Password div as follows:
data-parsley-equalto="#password"
into
data-parsley-equalto="#userForm_password"

There is no error anymore, the same is actually true for the case where one wants to change the password for the existing user admin.
data-parsley-equalto="#password"
into
data-parsley-equalto="#passwordForm_password"

However, I am not aware where in the source code I need to change this before producing the WAR file.

Maybe here? 

miso-lims-0.2.188/miso-web/src/main/webapp/scripts/form_user.js

Thank you in anticipation to solve this issue.

<input id="userForm_passwordConfirm" type="password" class="form-control parsley-success" data-parsley-errors-container="#userForm_passwordConfirmError" data-parsley-required="true" data-parsley-maxlength="100" data-parsley-pattern="^[^<>&amp;]*$" data-parsley-id="12" data-parsley-equalto="#password">

into

<input id="userForm_passwordConfirm" type="password" class="form-control parsley-success" data-parsley-errors-container="#userForm_passwordConfirmError" data-parsley-required="true" data-parsley-maxlength="100" data-parsley-pattern="^[^<>&amp;]*$" data-parsley-id="12" data-parsley-equalto="#userForm_password">
