### ISSUE TITLE
batch-uploading samples ?

### ISSUE THREAD

**Issue by Inkimar** [miso-lims/miso-lims#2074]
Hello,

New to miso.
Is it possible to batch-uplad samples according to a specific template ? 
from i.e. an excel-file with 96 files

-i

**Comment by sklages** [comment]
You can batch-create samples via the `create` button. 
What do you mean by `"according to a specific template"`?

**Comment by djcooke** [comment]
You can import an Excel spreadsheet into any of the bulk input forms. The data must be in the same format as it appears in MISO, and must have the same column headings
