### ISSUE TITLE
Password issues: not able to edit standard admin passwort nor set password for new user (This form seems to be invalid)

### ISSUE THREAD

**Issue by devNull2013** [miso-lims/miso-lims#2079]
Dear miso-lims team,

I am following the installation instruction for MISO detailed sample mode: https://miso-lims.github.io/miso-lims/latest/adm/compose-installation-guide. 

Login at http://localhost/miso works as expected.

Problems arise, when I edit the standard password of the admin user via "User Administration" => "Users" => "Login Name" => admin => "Reset Password" Section. I provide the Old Password (admin) and the New Password (something different than admin) and confirm this new password (No, I did not mistype :-) ). After clicking "Submit", an error message appears (=> see screenshots **admin** and **testuser** below)
The very same behaviour occurs when adding a new user and trying to set an initial password.
I also sampled the three check-boxes  (Admin, Internal and Active) but without any success.

This behaviour is reproducible with MISO version `0.2.188`, `0.2.189` and `0.2.190` (= latest) (didn't test versions < `0.2.188`).

My the docker-compose file: https://github.com/miso-lims/miso-lims/blob/develop/.docker/demo.detailed.yml

The miso log is here (and looks OK to me) : https://gist.github.com/devNull2013/93bd25ab2eb8e20cb0e20538e0d59082 

**admin**
![admin](https://user-images.githubusercontent.com/5655423/66308518-9f68d000-e907-11e9-900a-6b9106a31fa7.jpg)

**testuser**
![testuser](https://user-images.githubusercontent.com/5655423/66308586-c8896080-e907-11e9-8f06-e39e4e6884ee.jpg)

Thanks for any suggestions and help.

**Comment by djcooke** [comment]
It turns out this issue has already been fixed, and will be included in v0.2.191, which is due for official release on Thursday. If you'd rather try it out before then, you can build the Docker images from source:

```
git clone https://github.com/miso-lims/miso-lims.git
cd miso-lims
git checkout tags/v0.2.191
docker-compose -f compose.yml build
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password
echo "changeme" > ./.miso_db_password
docker-compose -f compose.yml up
```

I'll update the release notes for the affected versions to note this issue and the fix

**Comment by djcooke** [comment]
Closing the issue as fixed. Thank you for reporting it. Please reopen or create another issue if you continue to have trouble with this

**Comment by devNull2013** [comment]
Hello,

sorry for bothering again, but I`m struggling to get `v0.2.191` running.
Following your instructions, I'm able to build the images from source.

The login page is displayed as expected,

![misolims-1](https://user-images.githubusercontent.com/5655423/66467925-943bae80-ea85-11e9-9782-e8a6185b8d55.jpg)

but after providing the standard admin/admin combo, nothing happens. The browser windows stays empty and after reloading the login page, an `HTTP Status 404 - Not found` pops up.

![misolims-2](https://user-images.githubusercontent.com/5655423/66468307-3bb8e100-ea86-11e9-98cc-b4f4a456f0d5.jpg)

I checked my firewall rules, but nothing suspicious.
Do you know whats happening there?

Thanks
Christian

**Comment by djcooke** [comment]
Are there any errors showing up in `/storage/miso/log/miso_debug.log`?

**Comment by devNull2013** [comment]
Oh man, I forgot to check the miso.log by my self. Sorry...

Please find [>here<](https://gist.github.com/devNull2013/6ea0ff06d9a451e000c5b8be744525cd) the Error Stack.

**Comment by djcooke** [comment]
Ah, now you're experiencing the issue from #2078. The fix for that will be in v0.2.192, which will be prepared tomorrow, and officially released Oct. 24.

If you'd like to try it out before the release is prepared, you can do so using the following:

```
git clone https://github.com/miso-lims/miso-lims.git
cd miso-lims
git checkout develop
git pull
docker-compose -f docker-compose.detailed.yml build
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password
echo "changeme" > ./.miso_db_password
docker-compose -f docker-compose.detailed.yml up
```

**Comment by devNull2013** [comment]
Thanks, `v0.2.192-SNAPSHOT` works like a charm !

**Comment by djcooke** [comment]
Glad to hear it! Let us know if you have any more trouble
