### ISSUE TITLE
Creating new index sets not working properly?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2084]
I wanted to create a new index family with some indices (9nt), in my test case here:

```sql
CALL addIndexFamily('00 Sven Test', 'ILLUMINA',0,0);
CALL addIndex('00 Sven Test','Index 01','GGATGTTCT',1);
CALL addIndex('00 Sven Test','Index 02','CTTATCCAG',1);
```
The indices do show up when searching them via `Indices` in MISO. 
But the `Index Family` do **not** show up when creating or editing a library. No matter if in `bulk mode` or `single mode`. So selecting an index is impossible. 

We have been waiting more than 15min, hours.

Searching the logs for `Sven` does not yield any hits (`miso_debug.log` and `tomcat/logs`).

Any idea what I am missing and where to start looking for the source of this problem?

`MISO Version: 0.2.190`.

**Comment by djcooke** [comment]
Hi Sven,

It looks like we made a change recently to how `constants.js` gets updated, and it no longer does so automatically every 15 minutes anymore. I think this is a bug, but I'll have to discuss with the team. You can force a refresh by clicking "Refresh Constants" on the My Account page. Get to the My Account page by clicking your login name at the top right. The option is available for MISO administrators only.

**Comment by sklages** [comment]
"Refresh Constants" on the My Account page did it :+1: thanks.
