### ISSUE TITLE
Update 0.2.192 -> 0.2.194 : Migration V0970__auto_main.sql failed

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2124]
Just tried to update our MISO installation from `0.2.192` to `0.2.194` which resulted in an error:
```
WARNING: DB: FUNCTION miso_seqcore.decimalToString does not exist (SQL State: 42000 - Error Code: 1305)
Current version of schema `miso_seqcore`: 0960
WARNING: outOfOrder mode is active. Migration of schema `miso_seqcore` may not be reproducible.
Migrating schema `miso_seqcore` to version 0970 - auto main
WARNING: DB: Out of range value for column 'concentration' at row 9111 (SQL State: 22003 - Error Code: 1264)
ERROR: Migration of schema `miso_seqcore` to version 0970 - auto main failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0970__auto_main.sql failed
-------------------------------------
SQL State  : 22001
Error Code : 1264
Message    : Data truncation: Out of range value for column 'concentration' at row 9111
Location   : db/migration/V0970__auto_main.sql (/project/miso/2018/build_tools/flyway/5.2.4/file:/project/miso/2018/build_tools/flyway/5.2.4/jars/sqlstore-0.2.194.jar!/db/migration/V0970__auto_main.sql)
Line       : 6
Statement  : ALTER TABLE Library MODIFY COLUMN concentration DECIMAL(14,10)
```
Do I have to upgrade via `0.2.193` (although it is not tagged as `Release`)?

**Comment by djcooke** [comment]
Skipping releases should be fine as long as you follow the instructions in any upgrade notes. It looks like you may have a concentration value we didn't expect. As of version 0.2.193, concentration is limited to the range between -10,000 and 10,000 exclusive, but we can adjust this for the next release if you need a wider range. Can you run the below query and post the results?

```
SELECT MAX(concentration) FROM (
  SELECT MAX(ABS(concentration)) concentration FROM Sample
  UNION SELECT MAX(ABS(concentration)) FROM Library
  UNION SELECT MAX(ABS(concentration)) FROM LibraryAliquot
  UNION SELECT MAX(ABS(concentration)) FROM Pool
) AS data;
```

**Comment by sklages** [comment]
I had a look using your query and it turned out that there was a *library concentration* of **43000**!
I removed this weird value, ran again your query to be sure that there are no other weird concentration values and successfully updated `0.2.192 -> 0.2.193 -> 0.2.194`.

thanks :+1:
