### ISSUE TITLE
Feature or feature-request ?  importing genotypes

### ISSUE THREAD

**Issue by Inkimar** [miso-lims/miso-lims#2233]
Today I have a system, I import the following attributes  (packaged in a csv -fileor an excel-file ) .
The attributes are output from a scanner : postiion, tube-identifier and rack-idientifier then information about the species, position in WGS84, then the allelese ( now constrained to 16 Alleles)

***
Position | Tube | Container Name | UNIQUE-ID | IndividID | Species | Sex | date | Latitude (WGS84) | Longitude (WGS84) | Municipal | County | MU09 - 1 | MU09 - 2 | MU10 - 1 | MU10 - 2 | MU05 - 1 | MU05 - 2 | MU23 - 1 | MU23 - 2 | MU51 - 1 | MU51 - 2 | MU59 - 1 | MU59 - 2 | G10L - 1 | G10L- 2 | MU50 - 1 | MU50 - 2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
A01 | 4025809934 | 3000142742 | 13934298234234 | BI000030 | Ursus arctos | female | 2015-09-23 | 7144350 | 473722 | Stromsund  | Jamtlands| 104 | 116 | 151 | 151 | 127 | 127 | 173 | 176 | 142 | 150 | 246 | 248 | 172 | 182 | 130 | 136

***
before diving into misolims.
Is this a 'use case' / functionality that you support already or planning to support ?

Best, i

**Comment by djcooke** [comment]
Hello. Are you asking if you could import that spreadsheet as is into MISO in order to create samples? The spreadsheet would have to be formatted correctly to match the fields in MISO, and there would be other required fields.

MISO also does not have fields for latitude or any of the columns to the right of it in your example.

**Comment by Inkimar** [comment]
Hello @djcooke ,
Yes exactly, I have that header and then 96 records ( each of my racks has 96 viles) .
each rack has a unique id and each vile has a unique id.

This is squat from bears, and then they are plotted on a map.

Would it be possible to upload a csv- or an excel-file with a similiar template ( without the lat&lon then )?

This is a view from[ the UI.](https://archive.org/details/screenshot20200326genotypedetailssequencedatabase1)
best, i

**Comment by djcooke** [comment]
Genotypes cannot be recorded in MISO. You could import samples and racks, though the template would be very different and more information would be required.

**Comment by Inkimar** [comment]
thank you @djcooke .
Would it be possible, as the code is open source, to spend som time on importing genotypes and creating a view to displey them ?

-i

**Comment by djcooke** [comment]
MISO is not intended to store analysis results, so it's not a feature we'd want to merge into the main line.

You're welcome to develop the feature yourself, either by forking the repository, or by creating a separate piece of software for that purpose and integrating it with MISO however you see fit. If you have questions about developing MISO, you can chat with us on Gitter: https://gitter.im/miso-lims/developers
