### ISSUE TITLE
Upgrade 0.2.197 -> 0.2.202: Duplicate entry '3-2' for key 'uk_user_group'

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2248]
I am about to update from `0.2.197` to current version. Currently from `0.2.197` to `0.2.202` with the following error:

```
Migrating schema `miso_seqcore` to version 1000 - auto main
WARNING: DB: Duplicate entry '3-2' for key 'uk_user_group' (SQL State: 23000 - Error Code: 1062)
ERROR: Migration of schema `miso_seqcore` to version 1000 - auto main failed! Please restore backups and roll back database and code!
ERROR: 
Migration V1000__auto_main.sql failed
-------------------------------------
SQL State  : 23000
Error Code : 1062
Message    : Duplicate entry '3-2' for key 'uk_user_group'
Location   : db/migration/V1000__auto_main.sql (/project/miso/2018/build_tools/flyway/5.2.4/file:/project/miso/2018/build_tools/flyway/5.2.4/jars/sqlstore-0.2.202.jar!/db/migration/V1000__auto_main.sql)
Line       : 91
Statement  : INSERT INTO User_Group (users_userId, groups_groupId)
SELECT userId, @internalGroup
FROM User
WHERE INTERNAL = TRUE
```

I didn't find any **requirements** which have to be fulfilled before upgrading to `0.2.202`. 

What did I miss? What is there to do to fix this?

**Comment by djcooke** [comment]
This error shouldn't be possible since the group is created during the migration, and it shouldn't be possible to have multiple users with the same ID... Could you run the following SQL on your database (before the migration attempt) and paste the output in here?

```
-- Make sure there's only one user with userId 3
SELECT COUNT(*) FROM User WHERE userId = 3;

-- Make sure there is no group with groupId 2
SELECT COUNT(*) FROM _Group WHERE groupId = 2;

-- Make sure userId is the primary key
DESCRIBE User;
```

**Comment by sklages** [comment]
ok just one user with id=3 and no group with id=2.

`DESCRIBE User;` results in:

| Field | Type | Null | Key | Default | Extra |
| :--- | :--- | :--- | :--- | :--- | :--- |
| userId | bigint\(20\) | NO | PRI | NULL | auto\_increment |
| active | tinyint\(1\) | NO |  | 0 |  |
| admin | tinyint\(1\) | NO |  | 0 |  |
| fullName | varchar\(255\) | NO |  | NULL |  |
| internal | tinyint\(1\) | NO |  | 0 |  |
| loginName | varchar\(255\) | NO | MUL | NULL |  |
| roles | blob | YES |  | NULL |  |
| password | varchar\(255\) | YES |  | NULL |  |
| email | varchar\(255\) | YES |  | NULL |  |

**Comment by djcooke** [comment]
Looks as expected... I'm really not sure how this error is possible. Could you try again and see if the same thing happens?

**Comment by sklages** [comment]
## build MISO
```
cd $MISO_BUILD
rm -fr miso-lims.git
git clone https://github.com/TGAC/miso-lims.git miso-lims.git
cd miso-lims.git


VERSION=v0.2.202
git checkout $VERSION

[..]
HEAD is now at 94d084255 [maven-release-plugin] prepare release v0.2.202

mvn clean install | tee ../build_${VERSION}.log 2>&1
[..]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MISO LIMS .......................................... SUCCESS [  0.515 s]
[INFO] MISO Core .......................................... SUCCESS [ 17.059 s]
[INFO] MISO Integration Tools ............................. SUCCESS [ 19.682 s]
[INFO] miso-dto ........................................... SUCCESS [  5.583 s]
[INFO] MISO SQL Store ..................................... SUCCESS [  5.815 s]
[INFO] miso-service ....................................... SUCCESS [  4.462 s]
[INFO] MISO MVC ........................................... SUCCESS [ 20.546 s]
[INFO] pinery-miso ........................................ SUCCESS [  6.272 s]
[INFO] migration .......................................... SUCCESS [ 15.387 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 min
[INFO] Finished at: 2020-05-05T21:17:30+02:00
[INFO] Final Memory: 268M/4227M
[INFO] ------------------------------------------------------------------------
```

## deploy database
- stop all MISO/java processes
- delete old war file and its folder
- copy new WAR and some config files to its destination folders
- finally migrate database using flyway 5.2.4, this way:

```bash
migrate_database () {
    # https://github.com/miso-lims/miso-lims/blob/develop/RELEASE_NOTES.md#02174
    FW_VERSION="5.2.4"
    cd $MISO_HOME/build_tools/flyway/$FW_VERSION
    rm -f jars/sqlstore-*.jar
    unzip -xjo $CATALINA_HOME/webapps/ROOT.war 'WEB-INF/lib/sqlstore-*.jar' -d jars
    ./flyway \
      -user=XXXX \
      -password=YYYY \
      -url=jdbc:mysql://localhost:3307/miso_seqcore \
      -outOfOrder=true \
      -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration \
      -placeholders.filesDir=/path/to/storage/files/ \
      migrate
}
```

results in the same error:

```
Flyway Community Edition 5.2.4 by Boxfuse
Tue May 05 21:24:45 CEST 2020 WARN:
  Establishing SSL connection without server's identity verification is not recommended. [..]
Database: jdbc:mysql://localhost:3307/miso_seqcore (MySQL 5.7)
Executing SQL callback: beforeValidate
Successfully validated 135 migrations (execution time 00:00.684s)
Executing SQL callback: beforeMigrate
Current version of schema `miso_seqcore`: 0990
WARNING: outOfOrder mode is active. Migration of schema `miso_seqcore` may not be reproducible.
Migrating schema `miso_seqcore` to version 1000 - auto main
WARNING: DB: Duplicate entry '3-2' for key 'uk_user_group' (SQL State: 23000 - Error Code: 1062)
ERROR: Migration of schema `miso_seqcore` to version 1000 - auto main failed! 
       Please restore backups and roll back database and code!
ERROR:
Migration V1000__auto_main.sql failed
-------------------------------------
SQL State  : 23000
Error Code : 1062
Message    : Duplicate entry '3-2' for key 'uk_user_group'
Location   : db/migration/V1000__auto_main.sql (/project/miso/2018/build_tools/flyway/5.2.4/file:/project/miso/2018/build_tools/flyway/5.2.4/jars/sqlstore-0.2.202.jar!/db/migration/V1000__auto_main.sql)
Line       : 91
Statement  : INSERT INTO User_Group (users_userId, groups_groupId)
SELECT userId, @internalGroup
FROM User
WHERE INTERNAL = TRUE

```

now restoring database and rebuilding v0.2.197 .. :-(

**Comment by djcooke** [comment]
Ah, I think I found the issue... The `User_Group` table has no foreign key constraints, and you probably have orphaned rows in it. Run this SQL to fix:

```
DELETE FROM User_Group
WHERE users_userId NOT IN (SELECT userId FROM User)
OR groups_groupId NOT IN (SELECT groupId FROM _Group);
```

Confirm that 1 or more rows are affected, and then you should be able to migrate successfully.

I'll add the missing foreign key constraints.

**Comment by sklages** [comment]
Seems to work :-)
![image](https://user-images.githubusercontent.com/1837422/81211538-d0130400-8fd3-11ea-9b22-a458adf8146e.png)

I'll give it another try and report back ..

**Comment by sklages** [comment]
.. hm. Now I do not get an error, but it seems to take ages to migrate the database.
Since ~10 minutes I just see `Migrating schema `miso_seqcore` to version 1000 - auto main` and `mysqld` runs with 100% load ...

**Comment by djcooke** [comment]
It is a pretty heavy migration and will take a while on a large database

**Comment by sklages** [comment]
ok, ... after 13.5h not yet finished ... that's obviously "heavy". Some 18K samples .. and more libs.

That's our production system, never thought that it takes **so** long ..
Migration runs on a single "AMD Opteron 6176 SE" . 

I do not see if it is still a long way to go or if it is almost finished .. some wild guess?

If it takes too long I will cancel the migration and restore `0.2.197` for now. And find some better moment to update to `0.2.202` .

**Comment by djcooke** [comment]
10 minutes was not surprising, but it definitely shouldn't even 1 hour. I'm guessing either mysql has hung or is it's very low on resources to be running that slowly

**Comment by sklages** [comment]
Well, .. mysqld is running at 100% (still not finished) .. it is not the newest hardware, Opteron. But MISO has its own server, nobody else there ...

I would then cancel the migration, revert back to previous database version (backup) and start the migration again. What do you think?

**Comment by djcooke** [comment]
Yeah, might want to retry. Alternately, you could try running each statement from the [V1000 migration](https://github.com/miso-lims/miso-lims/blob/develop/sqlstore/src/main/resources/db/migration/V1000__auto_main.sql) one at a time to see if/where it gets stuck. Either do this on a copy of the database, or restore your backup afterwards even if it's successful, as this will interfere with future migrations otherwise.

**Comment by sklages** [comment]
```
SQL State  : 01S00
Error Code : 0
Message    : The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
```
How do I configure the JDBC driver to accept `CEST`?

**Comment by sklages** [comment]
`SELECT @@global.time_zone, @@session.time_zone;` gives `SYSTEM` and `SYSTEM`, `SELECT @@system_time_zone;` gives `CEST`.

**Comment by sklages** [comment]
OK, got it, I just added `serverTimezone=Europe/Berlin` to the `jdbc:mysql:` connection string.
I probably should do that `ROOT.xml` as well ...

**Comment by djcooke** [comment]
Out of curiosity, where did you see that error?

**Comment by sklages** [comment]
When running `flyway` ...

**Comment by sklages** [comment]
After restarting MySQL and restoring database I started the migration again.
After 90 Minutes still `Migrating schema `miso_seqcore` to version 1000 - auto main`.

I will try to figure out which step might cause the issue ... (by running your V1000 migration SQL step by step) ..

**Comment by sklages** [comment]
This is (the first?) step where `V1000 migration` is stuck:
![image](https://user-images.githubusercontent.com/1837422/81325585-de772380-9098-11ea-9bbe-6e61fc49202d.png)

... I will cancel it after more than one hour (still running). I will have to go back to `v0.2.197` for now. 

Any idea what is the problem here?

**Comment by djcooke** [comment]
I see what's happening now. `findParentWithLab` is going into an infinite loop. I'll have to patch the migration. I'll get a pull request in for that either this afternoon or tomorrow morning and will let you know how you can alter and run the migration before that's released, assuming you don't want to wait another 4 weeks (it's not going to get into the release that gets prepared this afternoon)

**Comment by djcooke** [comment]
I have a PR open to fix the issue for the next release. If you'd like to upgrade before then, you can just swap in the patched migration. I.e.

1. check out the version you want to deploy
2. download the patched migration: https://raw.githubusercontent.com/miso-lims/miso-lims/5d5c721fd6706fa64257314759a3a07d250c74a0/sqlstore/src/main/resources/db/migration/V1000__auto_main.sql
3. copy the patched migration into `/sqlstore/src/main/resources/db/migration/`, overwriting the existing V1000 migration
4. build and deploy as you normally would

**Comment by sklages** [comment]
`V1000` now runs fine. 

Migration now fails in `V1020`:
```
Migrating schema `miso_seqcore` to version 1020 - auto main
WARNING: DB: Incorrect datetime value: '0005-01-01 00:00:00' for column 'transferTime' at row 1484 (SQL State: 22007 - Error Code: 1292)
ERROR: Migration of schema `miso_seqcore` to version 1020 - auto main failed! Please restore backups and roll back database and code!
ERROR: 
Migration V1020__auto_main.sql failed
-------------------------------------
SQL State  : 22001
Error Code : 1292
Message    : Data truncation: Incorrect datetime value: '0005-01-01 00:00:00' for column 'transferTime' at row 1484
Location   : db/migration/V1020__auto_main.sql (<...>/flyway/5.2.4/file:<...>/flyway/5.2.4/jars/sqlstore-0.2.202.jar!/db/migration/V1020__auto_main.sql)
Line       : 8
Statement  : -- transferTime_timestamp
ALTER TABLE Transfer MODIFY COLUMN transferTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
```

I have expanded the jdbc url string, `jdbc:mysql://localhost:3307/miso_seqcore?serverTimezone=Europe/Berlin`

Any idea?

**Comment by sklages** [comment]
Btw, .. is it best to upgrade from one release to the next one or is it feasible to make it from `v0.2.197` directly to `v1.3.0`?

**Comment by djcooke** [comment]
There's no problem with upgrading several versions at once as you're trying to do. Just more changes at once and thus more potential issues, though they would happen the same either way.

As for your next issue...

1. In V1000, `transferDate` is created as a `date` column containing values from
    * Sample.receivedDate
    * Sample.distributionDate
    * Library.receivedDate
    * Library.distributionDate
    * LibraryAliquot.distributionDate
    * Pool.distributionDate
2. In V1010, `transferDate` is changed to a `datetime` column and renamed to `transferTime`
3. In V1020, `transferTime` is changed to a `timestamp` column, and this is where the error occurs

The problem is likely that you have a weird value stored in one of the columns that's used for `transferDate` in V1000. MySQL accepts different ranges for the different column types, though the year "0005" shouldn't work for any of them... These queries should help you locate the culprit anyway:

```
SELECT sampleId, receivedDate, distributionDate FROM Sample
WHERE receivedDate < '1970-01-01' OR distributionDate < '1970-01-01';

SELECT libraryId, receivedDate, distributionDate FROM Library
WHERE receivedDate < '1970-01-01' OR distributionDate < '1970-01-01';

SELECT aliquotId, distributionDate FROM LibraryAliquot
WHERE distributionDate < '1970-01-01';

SELECT poolId, distributionDate FROM Pool
WHERE distribtionDate < '1970-01-01';
```

Assuming those find something, you'll have to change the field to either `NULL` or a date > '1970-01-01'

**Comment by sklages** [comment]
```SQL
SELECT libraryId, receivedDate, distributionDate FROM Library
WHERE receivedDate < '1970-01-01' OR distributionDate < '1970-01-01';
```
found: `12330	0005-01-01`

No idea what happended here. Ugly typo which has been accepted. 

### Upgrading from `v0.2.197` to `v1.3.0`:
- change fishy receivedDate in MISO
- checkout `v1.3.0`
- replace patched `V1000__auto_main.sql`
- build and deploy just as before ...

Keep your fingers crossed :-)

**Comment by sklages** [comment]
Failed:
```
Migrating schema `miso_seqcore` to version 1020 - auto main
Migrating schema `miso_seqcore` to version 1030 - auto main
WARNING: DB: Duplicate entry 'MDL' for key 'uk_project_shortname' (SQL State: 23000 - Error Code: 1062)
ERROR: Migration of schema `miso_seqcore` to version 1030 - auto main failed! Please restore backups and roll back database and code!
ERROR: 
Migration V1030__auto_main.sql failed
-------------------------------------
SQL State  : 23000
Error Code : 1062
Message    : Duplicate entry 'MDL' for key 'uk_project_shortname'
Location   : db/migration/V1030__auto_main.sql (/project/miso/2018/build_tools/flyway/5.2.4/file:/project/miso/2018/build_tools/flyway/5.2.4/jars/sqlstore-1.3.0.jar!/db/migration/V1030__auto_main.sql)
Line       : 1
Statement  : -- unique_shortname
ALTER TABLE Project ADD CONSTRAINT uk_project_shortname UNIQUE (shortName)
```
Hopefully this does not mean that the project shortnames  need to be unique.
We have roughly 100 projects in MISO and one or two dozens of shortnames. We use the shortnames to somewhat group the projects internally (access groups on our unix fileservers).

**Comment by djcooke** [comment]
Hmm... Project short names are used differently between plain sample and detailed sample modes. In detailed sample modes, they are the primary identifier used for projects in several places, and thus must be unique. For plain sample mode, the project name is used in those places instead. The naming scheme also specifies whether or not duplicate project short names should be allowed.

I'm going to have to look into this some more to make sure I'm not missing anything, but I think we should probably remove the database constraint and let the naming scheme specify whether duplicates are allowed. Detailed sample mode should require that the naming scheme not allow duplicates though.

**Comment by sklages** [comment]
I am currently converting our `shortName`s for them to be finally unique. It does not make a big difference in any of our downstream usage of this value ..

I'll restart MISO update `v0.2.197` to `v1.3.0` afterwards, probably tomorrow.

**Comment by sklages** [comment]
So it is probably a good idea to keep the database constraint for shortName-uniqueness.

**Comment by sklages** [comment]
Finally, Upgrade directly to `Version: 1.3.0`:
```
Successfully applied 7 migrations to schema `miso_seqcore` (execution time 02:14.872s)
Executing SQL callback: afterMigrate
```

thanks for your support!
