### ISSUE TITLE
upgrade 0.2.196 => 0.2.199: ERROR: Table 'lims.RunPurpose' doesn't exist

### ISSUE THREAD

**Issue by chkohler** [miso-lims/miso-lims#2252]
Dear Miso-Team,
I'm reporting an issue I experienced when updating my docker-based miso installation from v0.2.196 => v0.2.199.
Version 0.2.196 runs fine (so does v0.2.197), but I suspect some DB migration failure when moving onwards to v0.2.199. 

The login screen appears as expected, but right after login with admin account, a Server Error occurs: 
![Screenshot 2020-05-06 at 16 57 46](https://user-images.githubusercontent.com/40832074/81192614-c16c2300-8fba-11ea-8f71-a558134be856.png)

Please find the output of my miso_debug.log in [ >> this gist << ](https://gist.github.com/chkohler/605997d7f4af86aa1828e998052e8feb)

This error is reproducible and does persist even after a clean checkout and a fresh docker build.
I also tried v0.2.201 and v0.2.202 with the same (negative) result.

When deploying v0.2.198, no explicit "Server Error" message pops up, but there is in fact no data fetched from the database. The respective fields (eg. "Samples" or "Libraries" etc) are just blank.

Please let me know what additional information you need.
Thanks in advance and sorry for bothering.

Christian

**Comment by djcooke** [comment]
Hello,

As you suggested, it seems like a database migration error. Assuming you're using docker compose and including a flyway service using the misolims/miso-lims-migration image, the database migration will happen automatically when you run `docker-compose up`.

Ideally, you backed up your database before attempting the upgrade. In this case, you should shut down docker-compose, restore your database, and then try bringing docker-compose up again (on latest version of MISO, or whichever you want to migrate to). Watch the output from the Flyway container, and if the migration fails, paste the output here.

If you don't have a backup (always make a backup!), just try shutting down docker-compose and bringing it back up again. Flyway will probably fail and let you know that your database contains a failed migration. Paste that output here, so we can figure out where it went wrong.

I'm realizing that the upgrade process when using Docker is not well documented, so I'll include fixing that as part of this issue.

**Comment by chkohler** [comment]
Dear Miso-Team,

I just did a fresh MISO installation on version 1.10.1. I suggest that the migration problem was an issue on our side. I'll now wait for the next update and see what happens.
For now, I'll close this issue.

Many thanks for your help and patience.

Cheers
Christian
