### ISSUE TITLE
flyway migration fails but can connect remotely via mysql

### ISSUE THREAD

**Issue by rbell92** [miso-lims/miso-lims#2258]
I am unable to migrate the database (initially) when setting up miso. 

I can access mysql from the remote application server using mysql -u 'misouser' -h 'database' -P '3306' -h 'ipofdatabase' -p 

flyway -user=misouser -password=miso_pass -url="jdbc:mysql://ipofdatabase:3306/lims?autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8&useSSL=false" -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate -placeholders.filesDir=/storage/miso/files/

There is a user with all privileges for the lims database with the miso username. The error in /var/log/mysqld.log on the sql database is: [Note] Aborted connection 7 to db: 'lims' user: 'miso' host: 'misodbip' (Got an error reading communication packets)

The error from flyway: SQL State  : 08001
Error Code : 0
Message    : Could not create connection to database server. Attempted reconnect 3 times. Giving up.

I have tried a few things: 
- disabling ssl
-max_allowed_packet=500M
- connect_timeout=30

I can access the database remotely using mysql but not flyway, the database is not opened for access over the internet, could this cause any problems?

**Comment by djcooke** [comment]
Hello,

What is the name of your database, and the name of the user with all privileges on the database? You've mentioned the user 'miso', and showed 'miso' in the error from mysqld.log, but used 'misouser' in the commands. In the example you gave of connecting to mysql, you didn't specify a database, but used 'lims' in the flyway command.

Try this to be sure you're using the same database and user:

```
# set up parameters (fill these in)
DB_NAME=
DB_HOST=
DB_USER=
DB_PASS=

# attempt mysql connection
mysql -h ${DB_HOST} -P 3306 -D ${DB_NAME} -u ${DB_USER} -p

# attempt flyway migration
DB_URL="jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8"
./flyway -user=${DB_USER} -password=${DB_PASS} -url=${DB_URL} -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate -placeholders.filesDir=/storage/miso/files/
```

**Comment by rbell92** [comment]
Hi thanks for your help. The user is miso in both instances I can actually connect now when I use url="jdbc:mariadb:// instead of url="jdbc:mysql://..

 I saw that this has happened to someone previously using centos 7: https://gitter.im/miso-lims/community?at=5d7a8f3761dfc75fce2bef87.  

I can now connect however there is a flyway error: ERROR: Found non-empty schema(s) `lims` without schema history table! Use baseline() or set baselineOnMigrate to true to initialize the schema history table. 

I have tried CREATE TABLE PlatformSizes (
  platform_platformId bigint(20) NOT NULL,
  partitionSize int NOT NULL,
  PRIMARY KEY (platform_platformId, partitionSize),
  CONSTRAINT fk_platform_size_platform FOREIGN KEY (platform_platformId) REFERENCES Platform (platformId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
However I get: ERROR 1215 (HY000): Cannot add foreign key constraint

**Comment by djcooke** [comment]
Ah, right... I'll add a note to the installation guide about using mariadb or mysql in the url.

As for the next issue, you should be working from a new (empty) database, so you can just drop and recreate it to be sure:

```
echo "DROP SCHEMA lims; CREATE SCHEMA lims;" | mysql -h ${DB_HOST} -P 3306 -D ${DB_NAME} -u ${DB_USER} -p
```

**Comment by rbell92** [comment]
Thanks that worked!
