### ISSUE TITLE
Pool.alias varchar(50): Row 1: Could not execute statement; SQL [n/a] ...

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2259]
Today we hit a limit with the pool `alias`. Due to large flowcells we try to give pools "meaningful" names. Usually we put in some customer and/or group names for lab people to be easily distinguished.

Could you extend `Pool.alias` from  `varchar(50)` to `varchar(255)`? 
Or can I easily (and safely) do this on my own?

**Comment by djcooke** [comment]
We can definitely increase the limit for pool alias, and should be able to get that into the next release (v1.5.0).

You could modify the column in your database to increase the size, but there is also validation on the pool page that will prevent saving a pool with an alias over 50 characters. To change that ahead of the release, you'd have to either modify the alias column's maxLength in form_pool.js ([here](https://github.com/miso-lims/miso-lims/blob/develop/miso-web/src/main/webapp/scripts/form_pool.js#L41)), rebuild and redeploy MISO, or you could do a hotfix on the live webapp by finding and modifying the same line in `${CATALINA_HOME}/webapps/ROOT/scripts/header_script.js` (header_script.js is created by concatenating all of MISO's js files)

**Comment by sklages** [comment]
Thanks a lot!
