### ISSUE TITLE
Q: Update to 1.5.0 : scientificName with trailing whitespace

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2269]
I wanted to prepare database for 1.5.0 upgrade. 
I just modified all those funny scientific names which have been entered over the time.

We do have some names with trailing whitespace, like:
`'Homo sapiens                          '`

Now, when running 
`UPDATE Sample SET scientificName = 'Homo sapiens' WHERE scientificName = 'Homo sapiens   some more whitespace                       ';`
I still get these names with whitespace when asking `SELECT DISTINCT scientificName FROM Sample;`.

How do I need to modify the UPDATE query to get rid of these names?

**Comment by djcooke** [comment]
You could use this to trim spaces from the start and end of all scientific names:

```
UPDATE Sample SET scientificName = TRIM(scientificName);
```

**Comment by sklages** [comment]
hmm, interestingly I still have the names with whitespaces (blue highlighted):
![image](https://user-images.githubusercontent.com/1837422/83799845-bafac500-a6a6-11ea-9771-dad766d6fbc4.png)

I am using DataGrip from JetBrains for queuring database ..

**Comment by sklages** [comment]
hmm, same with command line mysql:
```
| Homo sapiens							                                                                     |
| Homo Sapiens				                                                                        |
| Homo sapiens                                                                            |
```

**Comment by djcooke** [comment]
Ah, it's not spaces; it's tabs. Could use this to replace anything beginning with "Homo sapiens":

```
UPDATE Sample SET scientificName = "Homo sapiens" WHERE scientificName LIKE 'Homo sapiens%';
```

**Comment by sklages** [comment]
Works like a charm, thanks. 
Seems we sequenced more than 420 species. Wow, .. this will be a long dropdown list in v1.5.0 ..

**Comment by djcooke** [comment]
You'll be able to find entries quickly by typing the first couple letters. Let us know if it ends up being a pain though. Maybe we could add an option to archive ones that you're no longer using
