### ISSUE TITLE
Bad Request  No Run Purposes found with ID: 4

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2270]
After updating to v1.5.0:

I wanted to edit a scientific name, marking the name, and then edit.
Then I get:
![image](https://user-images.githubusercontent.com/1837422/83809384-a1fa1000-a6b6-11ea-8d61-20d95b3a20f3.png)

**Comment by sklages** [comment]
There is exactly one "run purpose": `Production`

**Comment by djcooke** [comment]
The Edit button is linking to the wrong page. I have a fix in. As a workaround, you can modify the URL to get to the intended page. Replacing "runpurpose" with scientificname"

e.g. `.../miso/scientificname/bulk/edit?ids=4`

**Comment by sklages** [comment]
ah, okay ..

**Comment by djcooke** [comment]
Should work correctly again starting in v1.7.0
