### ISSUE TITLE
Finding Related Items: [..].SampleImpl cannot be cast to [..].DetailedSample

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2271]
Selecting one or more samples and then clicking `Children` lets me select different options:
- Library
- Library Aliquot
- Pool

Choosing either of those options results in a new pop-up with an error:
`uk.ac.bbsrc.tgac.miso.core.data.impl.SampleImpl cannot be cast to uk.ac.bbsrc.tgac.miso.core.data.DetailedSample`

Reported as `ERROR: 500 error handling REST request` in `storage/log/miso_debug.log`.

`Version v1.5.0`, plain sample mode

**Comment by djcooke** [comment]
I see the problem and am working on a fix. It looks like the Children action has probably never worked in plain sample mode. Did it ever work for you before?

**Comment by sklages** [comment]
Well, I am working through the MISO tutorial to explore some features which have never been used by our lab. I am trying to get some new ideas to chnage/optimize lab workflows with new MISO features. Just to find some ways off the beaten track .. ;-)

We do have our fixed workflows, but some features are simply unused, e.g. Pool Orders, Worksets, Transfers, just to mention a few.

To make a long story short: I never used it befrore :-)

**Comment by djcooke** [comment]
Ah, ok. Was just curious whether you had used it before because looking at the code, I don't think it ever worked in plain sample mode. I do have a fix in now though, so it should work starting in v1.7.0
