### ISSUE TITLE
Exporting to Spreadsheet: not working (Excel)

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2272]
Selecting a bunch of samples and then `Download` lets me select some options.
E.g. `Tracking List` and `Microsoft Excel`. When clicking download, nothing happens. Changing output format to CSV or the `type` to something else does not change anything. 

No download ..

Nothing is reported in `storage/log/miso_debug.log`.

Version `v1.5.0`, plain sample mode, vivaldi browser (Linux)

**Comment by djcooke** [comment]
I see the issue and this looks like a very old bug as well. Has the Download action ever worked for you in plain sample mode?

**Comment by sklages** [comment]
nope, see #2271

**Comment by djcooke** [comment]
Fix is in. Should work starting in version 1.7.0
