### ISSUE TITLE
No drop-down options for 'Received By' field during Sample Creation

### ISSUE THREAD

**Issue by dfornika** [miso-lims/miso-lims#2277]
I'm having an issue with the interactive data entry table for sample creation. I'm running MISO v1.3.0 using docker-compose and the 'simple' sample configuration. The 'Received By' drop-down field doesn't give any options to choose from when I click the drop-down arrow. The 'Received From' field does give an option ('Not Specified (External)').

![Peek 2020-06-08 13-45](https://user-images.githubusercontent.com/145659/84078771-508ba280-a98e-11ea-8fda-f465e68b8dd9.gif)

**Comment by djcooke** [comment]
The Received By column is for choosing a group that has received the sample. For options to appear here, the logged in user must be a member of one or more user groups. The groups are also used when transferring samples (or other items) between groups within an organization. MISO administrators can create groups and add users to them

**Comment by dfornika** [comment]
Thanks @djcooke I've added a user to the 'Unspecified (Internal)' group and I can confirm that it appears in the drop-down now.

![Peek 2020-06-08 14-00](https://user-images.githubusercontent.com/145659/84080041-6601cc00-a990-11ea-8afe-a6b91abe699e.gif)

This resolves my issue.
