### ISSUE TITLE
Page not found after updating to 1.7.1

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2303]
Everything went fine during update.

Changes;

* `ROOT.xml`
```
cat root-xml.diff 
15c15
<   url="jdbc:mysql://localhost:3307/miso_seqcore?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;useLegacyDatetimeCode=false"
---
>   url="jdbc:mysql://localhost:3307/miso_seqcore?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=Europe/Berlin"
```

* `miso.properties`

Here I just added `miso.timeCorrection.uiZone:Europe/Berlin`

* MySQL `my.cnf`

Here I just added `default-time-zone='Europe/Berlin'`

After building and db migration I started MISO .. and got nothing but an empty page, stating that there is no page to be displayed (Vivaldi Browser), Firefox just shows an empty page with any comment.

This is what `miso_access_log.2020-07-05.txt` says:
```
IP Address - - [05/Jul/2020:07:17:20 +0200] "GET /miso/run/925 HTTP/1.1" 302 -
IP Address - - [05/Jul/2020:07:17:20 +0200] "GET /miso/login HTTP/1.1" 200 4985
IP Address - - [05/Jul/2020:07:45:06 +0200] "GET /login.jsp HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:45:20 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:46:37 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:46:43 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:46:44 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:46:45 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:46:45 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:47:16 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:47:16 +0200] "GET /favicon.ico HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:47:28 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:47:32 +0200] "GET / HTTP/1.1" 404 -
IP Address - - [05/Jul/2020:07:47:32 +0200] "GET /favicon.ico HTTP/1.1" 404 -
```

I have put catalina.log here, https://comanche.molgen.mpg.de/diverse/catalina.2020-07-05.log for you to have a look if necessary..

Any idea is appreciated :-)

For now I am going back to `1.5.0`.

**Comment by djcooke** [comment]
From your catalina log:

```
Caused by: java.sql.SQLException: The server timezone value 'CEST' represents more than one timezone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc timezone value if you want to utilize timezone support. The timezones that 'CEST' maps to are: Europe/Tirane, Europe/Andorra, Europe/Vienna, Europe/Minsk, Europe/Brussels, Europe/Sofia, Europe/Prague, Europe/Copenhagen, Europe/Tallinn, Europe/Berlin, Europe/Gibraltar, Europe/Athens, Europe/Budapest, Europe/Rome, Europe/Riga, Europe/Vaduz, Europe/Vilnius, Europe/Luxembourg, Europe/Malta, Europe/Chisinau, Europe/Tiraspol, Europe/Monaco, Europe/Amsterdam, Europe/Oslo, Europe/Warsaw, Europe/Lisbon, Europe/Kaliningrad, Europe/Madrid, Europe/Stockholm, Europe/Zurich, Europe/Kiev, Europe/Uzhgorod, Europe/Zaporozhye, Europe/Simferopol, Europe/Belgrade, Africa/Algiers, Africa/Tripoli, Africa/Tunis, Africa/Ceuta.
```

Did you restart MySQL after changing `my.cnf`? Also note that to use timezone names, you need to have populated the MySQL timezone tables. See https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html#time-zone-installation

**Comment by sklages** [comment]
No, I did not restart MySQL ... I will do so when updating.

So it's probably easiest to just put back `serverTimezone=Europe/Berlin` at the end of the jdbc:mysql connection string?

**Comment by djcooke** [comment]
Yes, I think specifying `serverTimezone` in the connection string should have the same effect, and doesn't require installing the timezones in MySQL.

Maybe we'll change this to our recommended setup since it is easier.

**Comment by sklages** [comment]
adding `serverTimezone=Europe/Berlin` to the jdbc:mysql connection string did the trick.
So MISO v1.7.1 is up and running :-)

thanks
