### ISSUE TITLE
migration 0.2.202 to 1.9.0: problem with detailed sample discriminators

### ISSUE THREAD

**Issue by LisaHagenau** [miso-lims/miso-lims#2325]
Hello,
I am trying to upgrade from 0.2.202 to 1.9.0. The migration fails with

```
ERROR: Migration of schema `miso` to version 1060 - auto main failed! Please restore backups and roll back database and code!
ERROR: 
Migration V1060__auto_main.sql failed
-------------------------------------
SQL State  : 42000
Error Code : 1304
Message    : (conn=155) PROCEDURE verifyDiscriminators already exists
Location   : db/migration/V1060__auto_main.sql (/home/miso/flyway-5.2.4/file:/home/miso/flyway-5.2.4/jars/sqlstore-1.9.0.jar!/db/migration/V1060__auto_main.sql)
Line       : 272
Statement  : -- fail migration if there is a mix of plain and detailed items
CREATE PROCEDURE verifyDiscriminators()
BEGIN
  IF (
    EXISTS (SELECT 1 FROM Sample WHERE discriminator = 'Sample')
    OR EXISTS (SELECT 1 FROM Library WHERE discriminator = 'Library')
    OR EXISTS (SELECT 1 FROM LibraryAliquot WHERE discriminator = 'LibraryAliquot')
  )
  AND (
    EXISTS (SELECT 1 FROM Sample WHERE discriminator <> 'Sample')
    OR (SELECT 1 FROM Library WHERE discriminator <> 'Library')
    OR (SELECT 1 FROM LibraryAliquot WHERE discriminator <> 'LibraryAliquot')
  ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Failed to determine all discriminators';
  END IF;
END
```
There are 3 samples with the default descriminator 'Sample' instead of the detailed sample class. These are all samples that belong to a custom created sample class in the sample category Tissue Processing. The custom children sample classes are updated correctly. 

Any idea on how to fix this?

Thank you

**Comment by djcooke** [comment]
Ah, I see the problem. That migration only handles tissue processing classes if they have a subcategory set, but it is possible to create tissue processing classes without a subcategory. I'll work on a fix

**Comment by djcooke** [comment]
I have a fix in PR now. After that is approved and merged, I'll release a patch for v1.9 that you'll be able to use. I'll post here when it is available

**Comment by LisaHagenau** [comment]
Great, thank you!

**Comment by djcooke** [comment]
v1.9.1 has been released with the fix: https://github.com/miso-lims/miso-lims/releases/tag/v1.9.1

It has been pushed to Docker Hub as well

**Comment by djcooke** [comment]
Closing ticket as the fix is available. Please reopen if you have any more trouble with the upgrade

**Comment by LisaHagenau** [comment]
Thank you, the migration worked. But now I am getting a 404 error trying to access MISO from the browser. I will probably open another issue for that if I can't get it fixed myself, since this issue was resolved.
