### ISSUE TITLE
Q: Where to change coloring of UI?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2329]
Is there coloring of the websites / UI centrally stored/configured and can be easily changed? I'd like to change the purple/lilac base color .. :-)

**Comment by djcooke** [comment]
All the colours are defined in the main css file. You can either modify it in the source before building (`miso-web/src/main/webapp/styles/style-full.css`) or in the webapp directory after deploying to Tomcat (`${CATALINA_HOME}/webapps/ROOT/styles/style.css`)

**Comment by sklages** [comment]
thanks
