### ISSUE TITLE
Cannot receive libraries for project with status "Unknown"

### ISSUE THREAD

**Issue by peterk87** [miso-lims/miso-lims#2361]
Hello,

One of my coworkers was trying to receive libraries for a project, filled in the necessary information and got an error with the project name not being filled in. The value in that field could not be changed either. We found out the issue was that the project status was set to "Unknown" rather than "Active". 

It would be nice to have a warning that you cannot receive any libraries or samples for a non-active project and have the "Receive" button disabled until the status has changed.

Thanks!
Peter

**Comment by djcooke** [comment]
Hello,

We actually didn't intend to prevent receiving libraries based on project status. The project dropdown on the bulk page is filtered to only show active projects though. Normally this makes sense to keep the dropdown options list shorter, but if you're on the Edit Project page for a project not marked as active, then that project should not be filtered out.

Thanks for reporting. We'll get a fix in for this soon.

**Comment by djcooke** [comment]
Fixed in #2363

**Comment by peterk87** [comment]
Thanks for the quick fix @djcooke !
