### ISSUE TITLE
Docker pull fails for 1.13.0

### ISSUE THREAD

**Issue by nickp60** [miso-lims/miso-lims#2365]
Hi miso-lims folks!  I am trying to get the demo working, but on my machine (fresh cloud vm running Debian GNU/Linux 10 (buster)) the docker compose command fails when trying to pull the webapp:

```
docker pull misolims/miso-lims-webapp:1.13.0 
...
...
...
error pulling image configuration: unknown blob
```

The command succeeds with 1.12.0, so I'll be evaluating the software with that version...

**Comment by djcooke** [comment]
Hi. Thanks for reporting this. Docker Hub is showing a compressed size of 0B for the 1.13.0 image, so something must have gone wrong when uploading it. I'll give it another try.

**Comment by djcooke** [comment]
Looks good now. Please reopen the ticket if you have any more trouble with it.
