### ISSUE TITLE
pinery-miso : java.lang.IllegalStateException: pinery.propertiesFile not set

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2378]
I haven't been using Pinery for a while. Now I am starting to migrate my "database query scripts" (samplesheet writer, info retrieval etc) from SQL queries to Pinery.

I always build and deploy pinery together with every MISO update. But now I wanted to use it (just as I did a while ago) and run into the following error, e.g with `samples` endpoint:

```
curl -X GET --header "Accept: application/json" "http://miso.server/pinery-miso/samples"
```

Error:
```
[..]
java.lang.IllegalStateException: pinery.propertiesFile not set
[..]
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
[..]
</pre><p><b>Root Cause</b></p><pre>org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:&#47;project&#47;miso&#47;2018&#47;tomcat&#47;webapps&#47;pinery-miso&#47;WEB-INF&#47;lib&#47;pinery-service-2.13.0.jar!&#47;ca&#47;on&#47;oicr&#47;pinery&#47;service&#47;impl&#47;CacheScheduler.class]; nested exception is java.lang.IllegalStateException: pinery.propertiesFile not set
[..]
```
Now I am wondering about `pinery.propertiesFile not set` ... where do I set this?

I do have:
```
tomcat/webapps/pinery-miso.war
tomcat/webapps/pinery-miso/WEB-INF/classes/pinery-miso-config.xml
tomcat/webapps/pinery-miso/WEB-INF/classes/pinery-miso.properties
tomcat/work/Catalina/miso.server/pinery-miso
```

Checking the API docs results in the same error:
```
links http://miso.server:8088/pinery-miso/api-docs/index.html

500 Internal Server Error
```

My latest MISO update (1.15.1) was successful, MISO itself and Pinery:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MISO LIMS .......................................... SUCCESS [  1.168 s]
[INFO] MISO Core .......................................... SUCCESS [ 17.127 s]
[INFO] MISO Integration Tools ............................. SUCCESS [ 22.402 s]
[INFO] miso-dto ........................................... SUCCESS [  6.848 s]
[INFO] MISO SQL Store ..................................... SUCCESS [  7.583 s]
[INFO] miso-service ....................................... SUCCESS [  4.889 s]
[INFO] MISO MVC ........................................... SUCCESS [ 27.217 s]
[INFO] pinery-miso ........................................ SUCCESS [  7.562 s]
[INFO] migration .......................................... SUCCESS [ 16.388 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

So obviously I am doing something incredibly wrong here, probably some severe (old) mis-configuration.

Can you help on that?

**Comment by djcooke** [comment]
You should have a context config file (e.g. `pinery-miso.xml`) in `${CATALINA_HOME}/conf/Catalina/localhost/`. The context config specifies the location of the properties file (`pinery.propertiesFile`), which should probably be in the same directory.

See the [Pinery-MISO readme](https://github.com/miso-lims/miso-lims/blob/develop/pinery-miso/README.md), which links to example config files.

**Comment by sklages** [comment]
.. yes, and another one in `${CATALINA_HOME}/conf/Catalina/miso.molgen.mpg.de/pinery-miso.xml`...  that I haven't edited.

And I had a typo(?) in my xml file template: `miso.propertiesFile` instead of `pinery.propertiesFile` .. 

However, now it works like a charm :-)

thanks.
