### ISSUE TITLE
Samples: `Project` dropdown menu limited?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2412]
We have quite a few projects configured in MISO, currently > 109.

When creating a sample via `Samples`/`Create` the dropdown menu for `Project` is limited, here to `PRO103`. We do have configured more projects. 

Is this actually intended? Can this limit be extended?

Adding samples by selecting a `Project` and then `Samples/Create` works though ...

**Comment by djcooke** [comment]
There shouldn't be a limit to the number of options. The dropdown only includes projects with status set to "Active" though. Might this be the issue?

**Comment by sklages** [comment]
Yes, you are right! That is the "problem". For some reason project status is "Unknown"!?
