### ISSUE TITLE
Highlighted fields/cells for sample data entry can be difficult to see for those with color blindness

### ISSUE THREAD

**Issue by peterk87** [miso-lims/miso-lims#2444]
Hello,

When entering information for samples, if a field is missed and highlighted ("Please fix highlighted cells"), the coloring used may be difficult to see for those with color blindness. 

Would it be possible to use a more intense color or maybe an asterisk to help differentiate mandatory fields from optional fields?

Thanks!

**Comment by djcooke** [comment]
Hello,

This is a good point. I think two changes are required to make it more accessible.

1. add asterisks to the column names to indicate required cells
2. indicate the cells with errors in a second way after attempting to save - maybe with an icon, or by listing the problems above the table

**Comment by peterk87** [comment]
Those changes would be really great! Text description of cells with errors and why there are errors would be amazing and save a lot of time for new users.

**Comment by djcooke** [comment]
#2451 implements both proposed changes
