### ISSUE TITLE
Show full text and abbreviation for "Code" field on the "Edit Libraries" page

### ISSUE THREAD

**Issue by peterk87** [miso-lims/miso-lims#2445]
Hello,

On the "Edit Libraries" page, the "Code" field only displays the abbreviation and not the full text for the library design. Would it be possible to show both? New MISO users may not be familiar with the abbreviations. 

Thanks!

**Comment by djcooke** [comment]
Yes, that is a good suggestion, thanks! We already show both on the single Edit Library page, and should update the bulk page to be similar.

**Comment by djcooke** [comment]
https://github.com/miso-lims/miso-lims/pull/2594
