### ISSUE TITLE
What should I do after installing MISO?

### ISSUE THREAD

**Issue by GHKosovo** [miso-lims/miso-lims#2467]
I cannot use any of its functions at all after installed and running the MISO using Docker Compose.
My installation mode is Detailed sample mode.I log in my miso website and counld't do anythings
like the picture show below:
![image](https://user-images.githubusercontent.com/26101252/110884709-7a5c6600-8320-11eb-8a90-45bd5a76783e.png)
No dashborad,No Search navbar and so on.
When I click 'Preparation - Pool Orders',it shows like this:
![image](https://user-images.githubusercontent.com/26101252/110886473-a9c0a200-8323-11eb-9d30-9815b54b5da4.png)

I don't know how to go on my miso!

**Comment by GHKosovo** [comment]
....

**Comment by djcooke** [comment]
Hello. You have closed the issue. Are you still having trouble?

**Comment by djcooke** [comment]
Oh, I see. Duplicate of #2468

**Comment by GHKosovo** [comment]
Yes, they are the same issues.Sorry, I committed it twice because the network problem.
