### ISSUE TITLE
What should I do After installed MISO using Docker Compose next?

### ISSUE THREAD

**Issue by GHKosovo** [miso-lims/miso-lims#2468]
I cannot use any of its functions at all after installed and running the MISO using Docker Compose.
My installation mode is Detailed sample mode.I log in my miso website and counld't do anythings
like the picture show below:
![image](https://user-images.githubusercontent.com/26101252/110884709-7a5c6600-8320-11eb-8a90-45bd5a76783e.png)
No dashborad,No Search navbar and so on.
When I click 'Preparation - Pool Orders',it shows like this:
![image](https://user-images.githubusercontent.com/26101252/110886473-a9c0a200-8323-11eb-9d30-9815b54b5da4.png)

I don't know how to go on my miso!

**Comment by djcooke** [comment]
Hello. Can you provide some more info to help us determine the problem?

* What MISO version are you running?
* Run the following query on your database and paste the results here. This will tell us if there was a problem setting up the database.
  ```
  SELECT * FROM flyway_schema_history;
  ```
* Check to see if there are any stack traces in `${miso.baseDirectory}/log/miso_debug.log` and paste them here if so

**Comment by GHKosovo** [comment]
Sorry, so late to reply you. I have a rest on weekend. 

I found some error messages in the log files.

My miso version is the lastest version. I pulled it from the docker hub.

And I put some error messages and sql query results into some files below.

#Sql query results
[SqlQueryResult.xlsx](https://github.com/miso-lims/miso-lims/files/6138438/SqlQueryResult.xlsx)

#Error Messages
[ErrorMessage.txt](https://github.com/miso-lims/miso-lims/files/6138444/ErrorMessage.txt)

**Comment by djcooke** [comment]
Your database looks good, but the errors in your log are related to database tables and fields from an older version, which have since been removed. Can you verify the version of MISO you have running? It should appear at the bottom of every page of the web app

**Comment by GHKosovo** [comment]
The version is 1.18.0.
![image](https://user-images.githubusercontent.com/26101252/111169549-0818a980-85de-11eb-8700-df0580a92ffa.png)

**Comment by djcooke** [comment]
Your database is at V1230, which goes with MISO version 1.23.0. If you update the web app to 1.23.0, it should work with your existing database.

**Comment by GHKosovo** [comment]
Thank you.It works.Thank you for your help.Have a nice day!
