### ISSUE TITLE
Add new types to IlluminaExperiment.java for Illumina sample sheet CSV creation

### ISSUE THREAD

**Issue by peterk87** [miso-lims/miso-lims#2532]
The 3 types in the IlluminaExperiment enum do not quite fit the type of sequencing experiments performed at my lab. We typically set "Application" to "FASTQ Only" with "Workflow" set to "GenerateFASTQ". Would it be possible to add 2 new types to the Type dropdown when creating a sample sheet CSV from a sequencing pool?

https://github.com/miso-lims/miso-lims/blob/54408a8619628fc0c28cfd478e86800e2cada1e4/core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java#L26

Below are the types I'd like to add to the IlluminaExperiment enum:

```java
  FASTQ_ONLY_NEXTERA_XT("FASTQ Only (Nextera XT)") {

    @Override
    protected void applyAttribute(Map<String, String> header, Map<String, String> settings) {
      header.put("Workflow", "GenerateFASTQ");
      header.put("Application", "FASTQ Only");
      header.put("Assay", "Nextera XT");
      settings.put("ReverseComplement", "0");
      settings.put("Adapter", "CTGTCTCTTATACACATCT");
    }
  },
  FASTQ_ONLY_TRUSEQ_NANO_DNA("FASTQ Only (TruSeq Nano DNA)") {

    @Override
    protected void applyAttribute(Map<String, String> header, Map<String, String> settings) {
      header.put("Workflow", "GenerateFASTQ");
      header.put("Application", "FASTQ Only");
      header.put("Assay", "TruSeq Nano DNA");
      settings.put("ReverseComplement", "0");
      settings.put("Adapter", "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA");
      settings.put("AdapterRead2", "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT");
    }
  }
```

**Comment by djcooke** [comment]
It would probably be ideal to make it so these can be defined in MISO without any code changes, but it doesn't hurt to add them in this form in the meantime. Are you able to make a pull request?

**Comment by peterk87** [comment]
Hi @djcooke adding the ability to load this info from a config file would be great.

I've created a PR at #2533

**Comment by djcooke** [comment]
Change was merged
