### ISSUE TITLE
Q: 1.31.0 already "safe"?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2538]
Well, .. I miss the samplesheet generation  ;-)

Is it already (more or less) safe to use not-yet-officially-released-1.31.0 or are you expecting any issues. Looks like it's working stable in your lab quite some time now :-)

**Comment by djcooke** [comment]
Yes, I'd go ahead and use 1.31.0 if you'd like. We've been using it in production for two weeks now and haven't had any issues. It should get an official release later today I think
