### ISSUE TITLE
FR: Attachments and/or Notes for Index Families

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2546]
Would be nice to be able to add attachments to index families (per family, in `Edit Index Family`). There are quite a lot of manufacturers and kits, all with their own index sets. Many somewhat similar .. so here we could keep some protocols and/or original index information from the manufacturer.

Alternatively or additionally maybe "Notes", basically similar to `Sequence Runs`.

We currently have 56 index families in MISO :-)

**Comment by sklages** [comment]
Is this something you consider to implement? If not we can close this issue IMHO ...

**Comment by djcooke** [comment]
We don't currently have plans to implement this, but it's something we may consider in the future
