### ISSUE TITLE
Checking Pinery-MISO (v1.32.0) throws an error 404

### ISSUE THREAD

**Issue by wgatb** [miso-lims/miso-lims#2550]
Dear Miso-Team,

I'm asking for your support.

For handling large amount of data in the laboratory the MIS-LIMS system version 1.32.0
(Earlham Institute, Ontario Institute for Cancer Research) was installed.
We have also installed Pinery-MISO for exporting MySQL data as described here:
https://github.com/miso-lims/miso-lims/tree/develop/pinery-miso

Building the software has been accomplished successfully.
After restarting tomcat we use the Webserver via URL http://localhost:8080/ .

Then we logged in to check Pinery-MISO using URL http://localhost:8080/pinery-miso/api-docs/index.html 
as decribed in the README.
This will terminate with Error Code : 404 (Not Found)
(Visible in logfile.)

What went wrong and how can I debug this process?

Thank you very much for any help.

Cheers
Wilfried

localhost_access_log.txt:
________________________
192.168.30.9 - - [19/Jul/2021:10:30:42 +0200] "GET /pinery-miso/api-docs/index.html HTTP/1.1" 404 3220
192.168.30.9 - - [19/Jul/2021:10:31:22 +0200] "GET /pinery-miso/api-docs/index.html HTTP/1.1" 404 3220
192.168.30.9 - - [19/Jul/2021:10:33:36 +0200] "GET /pinery-miso/api-docs/index.html HTTP/1.1" 404 3220

**Comment by djcooke** [comment]
Hi @wgatb,

The URL in the documentation is outdated (I'll update that!). Try http://localhost:8080/pinery-miso/swagger-ui.html. You can also try http://localhost:8080/pinery-miso/ which shows some health stats, and also has a link to the API docs at the top.

If it still isn't loading, make sure you named the .war file in the tomcat webapps directory `pinery-miso.war`, as that is what causes it to use the `/pinery-miso/` URL space. You can also check `catalina.out` in the Tomcat `logs` directory for errors deploying the webapp.

**Comment by wgatb** [comment]
Hello djcooke,
  the hint to check the catalina.out file was relevant.
I found this error:
file:/opt/apache-tomcat-8.5.35/conf/Catalina/localhost/pinery-miso.xml; lineNumber:
 4; columnNumber: 2; The markup in the document following the root element must be well-formed. a syntax error in file pinery-miso.xml.
...
Thank you for your support!
Wilfried
