### ISSUE TITLE
FR: Pinery Endpoint "SAMPLES": LIB-ID -> missing barcode name

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2561]
When using Pinery (`SAMPLES` endpoint), I get almost all relevant infos,

For a LIB ID I get some attributes of the used barcodes:

```
"name" : "Barcode Kit",
"value" : "Ovation RRBS Single Index"

"name" : "Barcode",
"value" : "GCACTA"
```

What I am really missing here, is the **index name** , e.g. I'd like to see:

```
"name" : "Barcode Kit",
"value" : "Ovation RRBS Single Index"

"name" : "Barcode Name",
"value" : "BC04"

"name" : "Barcode Sequence",
"value" : "GCACTA"
```

Or is there any other simple way/endpoint to get this information using Pinery?

**Comment by djcooke** [comment]
The index name is not currently included in Pinery, but it could be added as you suggest. The existing "Barcode" attribute would not be renamed though

**Comment by sklages** [comment]
That would be fantastic!
For large pools on large NovaSeq flowcells this would greatly help to track down index (mixup) issues .. :-)

**Comment by sklages** [comment]
@djcooke is this something you actually plan to implement? Or is this something that is more towards the bottom of the MISO to-do list? 

I don't want to bug you, I just need to decide for myself how to proceed internally here to get the names :-)

**Comment by djcooke** [comment]
@sklages I'd like to get this done for you at some point, but can't promise any timeline as we're currently very busy

**Comment by djcooke** [comment]
@sklages Finally got to this! It will be included in the next release: https://github.com/miso-lims/miso-lims/pull/2676

There are two new attributes: "Barcode Name" and "Barcode Two Name" (each only included when appropriate of course)
