### ISSUE TITLE
Local build Issue

### ISSUE THREAD

**Issue by Owen2015** [miso-lims/miso-lims#2620]
Hi, I try to build miso locally but encounter an error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project core: Fatal error compiling: invalid flag: --release -> [Help 1]
What should I do to solve this? Is there documents for how to build to project locally?

**Comment by djcooke** [comment]
What JDK version are you using? MISO uses Java 11 and should build with any JDK from 11-15. I think there will be issues with JDK16+

**Comment by Owen2015** [comment]
Tremendous thanks!! After I change the jdk from JDK8 to JDK13, errors  disappear.

**Comment by Owen2015** [comment]
Tremendous thanks!! After I change the jdk from JDK8 to JDK13, errors  disappear.
