### ISSUE TITLE
Vulnerability issue on miso log4j

### ISSUE THREAD

**Issue by jayramr** [miso-lims/miso-lims#2639]
Hello,

My IT pointed that the docker installation version running a vulnerable version of log4j on apache tomcat

Path -> /var/lib/docker/overlay2/***/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/log4j-core-2.15.0.jar

Refer - https://logging.apache.org/log4j/2.x/security.html

Thanks
Jay

**Comment by jayramr** [comment]
Below is just a workaround 
#cd 
 /var/lib/docker/overlay2/*****/merged/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/
zip -q -d  log4j-core-2.15.0.jar org/apache/logging/log4j/core/lookup/JndiLookup.class

I would prefer to patch to latest version , Even i downloaded 2.17.5 and put in the same folder, but after that this is not working properly, hence i reverted back

**Comment by djcooke** [comment]
Hello,

Thanks for reporting this. MISO was updated to use log4j 2.17.1 several releases ago. Unfortunately, it seems we didn't push Docker images for those releases to Docker Hub.

I have just pushed the latest release to Docker Hub now. Please update to the latest version available.

I am looking into improving our release procedure so that we don't miss doing this in the future.

**Comment by djcooke** [comment]
It's unclear what happened here though. Can you run the following to see if everything starts up properly?

```
docker-compose -f demo.detailed.yml down
docker-compose -f demo.detailed.yml up -d
```

**Comment by djcooke** [comment]
Ah, I misunderstood and didn't realize you were rebooting the host system. If you want the container to survive reboot, you do need `restart: always` for the `nginx` service in the compose file as you suggested. It's definitely a mistake that we didn't include that in the demo compose setups, so I will add it for the next version

**Comment by jayramr** [comment]
Thanks @djcooke all good with my setup. 

Feel free to close this thread :)

**Comment by djcooke** [comment]
Glad to hear it's working now!

Updated restart procedure in https://github.com/miso-lims/miso-lims/pull/2641
