### ISSUE TITLE
User permission access issues 

### ISSUE THREAD

**Issue by jayramr** [miso-lims/miso-lims#2660]
Hi Team,

We are testing the miso plain/detailed docker compose installation and did a couple of sample, library creation operations. 

Currently we have some concerns how the delegations/privileges given to normal users. 

Here is my scenerio

There is only one admin user which is admin
Group 1 , consist of 5 normal users
Group 2, consist of 4 normal users

For normal users, i enabled the "Internal and Active" flag. And there are any other option i didn't seen to customize 

Questions

1) Normal user having the full access to delete or update the samples or libraries.

2) Normal user can able to see the contents of all samples / libraries

Please update what will be the best way or if this is an issue, please fix the same on the next docker image release. We only focussing on docker-compose based instalaltions

Thanks
Jay

**Comment by djcooke** [comment]
Hi Jay,

1. Normal users can edit any samples, libraries, and most other things in MISO. Normal users can only delete items that they created though. Admin users can delete items that anyone created, and can also create/edit configuration items such as sample types and library designs.
2. This is correct - All MISO users have access to see everything. There are no plans to add any more detailed permissions to MISO at this time

**Comment by jayramr** [comment]
Dear Dillian,

Thanks for the update on this. 

I totally agree on your point that there are no plan for any detailed permission 

Is that possible could you shed some lights how this can be doable from db-level or file-level from the miso application. I'm planning to customize this application, before going to production in a secure way. 

Awaiting for your reply on the same 

Thanks
Jay

**Comment by djcooke** [comment]
If you want to set different permissions on projects, samples, or other items in MISO, you will have to fork the repository and develop that feature. There is no way to accomplish this using the database or file system with MISO in its current form.

I am closing the ticket as we do not plan to work on this, but please feel free to ask if you have other questions.
