### ISSUE TITLE
Password reset in miso throwing error "Not Found 404"

### ISSUE THREAD

**Issue by jayramr** [miso-lims/miso-lims#2666]
Hi,

I tried to reset my normal user password and once i submit I'm getting error as  "Not Found 404", but after reloading the page, the system is taken the new password.

But this error "Not Found 404" coming the password reset page thinks that this is not successfully passed. 

On miso_debug log can see "2022-05-25 08:56:21 WARN: No mapping found for HTTP request with URI [/miso/users/15] in DispatcherServlet with name 'miso'" 

Please check 

Thanks
Jay

**Comment by djcooke** [comment]
Fix will be in next release: https://github.com/miso-lims/miso-lims/pull/2675

Thanks for reporting this!
