### ISSUE TITLE
Q: Put SAM ID into Alias when creating samples?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2687]
is there a way to somehow insert the automatically created SAMnnn ID into the "Alias" when creating samples bulk mode?

E.g. creating a sample with a customer name like "cancerABC" .. in MISO I'd like to put something like `cancerABC_S$X` where $X will be replaced by the MISO sample ID (SAM). maybe even zero-padded.

I simply would like to (automatically) have the SAM-ID in the sample alias when creating samples.

Is this possible in some way?

**Comment by djcooke** [comment]
This is not currently possible. It would be possible (with some development work) to add a sample alias generator that includes the sample ID, but the generator has to generate the entire alias. If you wanted to enter the "cancerABC" part and have the generator add onto it, that is not how MISO's alias generators work
