### ISSUE TITLE
Q: 1.47.0, new password requirements

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2691]
With `1.47.0`the password requirements have changed.

- minimum password length: 8
- minimum complexity: must contain at least 3 of the following: uppercase letters, lowercase letters, numbers, special characters

These requirements are not (fully) met with our current user's passwords in MISO. Will I expect problems when updating MISO from `1.43.2` to current `1.47.1`?

Sure, after updating all our lab members can update their passwords to match the new criteria. But hopefully the old passwords are not stopping from working immediately.

**Comment by djcooke** [comment]
Existing passwords are not affected by the change. They are encrypted in the database, so we have no way of knowing whether they meet the new requirements. If you wanted to be sure, you would have to reset all existing user passwords.

**Comment by sklages** [comment]
thanks for the quick response! Got it :-)
