### ISSUE TITLE
fetch Run information from Runid

### ISSUE THREAD

**Issue by bassanio** [miso-lims/miso-lims#2706]
Hi,

Can someone please assist me on how to connect mysql tables (query)to fetch Run informations eg (SampleId,Sample name,Index1 ,index2,lane,Pool, Library,LibraryID) by using  Run ID only . I need to create some statistics based on these results.

Thanks in advance

**Comment by djcooke** [comment]
Hello,

You can use this as the base of your query:

```
SELECT ...
FROM Run r
JOIN Run_SequencerPartitionContainer rspc ON rspc.Run_runId = r.runId
JOIN SequencerPartitionContainer spc ON spc.containerId = rspc.containers_containerId
JOIN _Partition part ON part.containerId = spc.containerId
JOIN Pool pool ON pool.poolId = part.pool_poolId
JOIN Pool_LibraryAliquot pla ON pla.poolId = pool.poolId
JOIN LibraryAliquot la ON la.aliquotId = pla.aliquotId
JOIN Library l ON l.libraryId = la.libraryId
JOIN Sample s ON s.sampleId = l.sample_sampleId
```

If you are using detailed sample mode, you can use Sample.parentId to find the next sample parent and work your way up the hierarchy. There's also a SampleHierarchy table that helps to find any sample's parent tissue and identity samples.

**Comment by bassanio** [comment]
Hello,

Thank you very much . for me the above code works.
