### ISSUE TITLE
FR: Element Biosciences AVITI Sequencer Support

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2850]
Are you somehow planning to add support for [Element Biosciences AVITI Sequencer](https://www.elementbiosciences.com/)?

**Comment by djcooke** [comment]
We don't have plans for this in either MISO or Run Scanner at this time. The best you can do currently is create it as an instrument model and choose one of the existing platforms. It's not ideal that you'll have to choose a platform that doesn't make sense, but it will allow you to create runs

**Comment by sklages** [comment]
@djcooke - ok, thanks. Not perfekt, but at least it seems to work ..
