### ISSUE TITLE
No page reloading after file upload (attachment)

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2854]
After attaching a file to a run, the page needs to be reloaded manually (F5) in order to show the attachment in the table.
In previous versions the page has been refreshed automatically after uploading a file.

Version: 2.12.0

**Comment by djcooke** [comment]
Thanks for reporting this. We'll have a fix in soon

**Comment by djcooke** [comment]
Should be included in the next release **after** 2.13.0 https://github.com/miso-lims/miso-lims/pull/2857
