### ISSUE TITLE
login not possible after update

### ISSUE THREAD

**Issue by LisaHagenau** [miso-lims/miso-lims#2860]
Hello,
I have just updated our baremetal installation from v1.9.1 to v1.51.2. I am currently running Java 11 and Tomcat 9. The migration was successful and the tomcat server started, but I can't login on the browser site with any of the logins that previously worked. I can see the users and hashed passwords in the database, so it should work. If I try the login with a fake login name and password, I get an "Access denied!" message in the browser, which doesn't happen if I use a valid login. I'm kind of stumped here...

This is the output of the catalina.log:

> 12-Mar-2024 16:04:33.901 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/9.0.8
12-Mar-2024 16:04:33.907 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Apr 27 2018 19:32:00 UTC
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         9.0.8.0
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-200-generic
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.19+7-post-Ubuntu-0ubuntu118.04.1
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
12-Mar-2024 16:04:33.908 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
12-Mar-2024 16:04:33.909 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
12-Mar-2024 16:04:33.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
12-Mar-2024 16:04:33.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
12-Mar-2024 16:04:33.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
12-Mar-2024 16:04:33.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
12-Mar-2024 16:04:33.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsecurity.method=jdbc
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx768M
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
12-Mar-2024 16:04:33.917 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
12-Mar-2024 16:04:33.922 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
12-Mar-2024 16:04:33.923 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.3].
12-Mar-2024 16:04:33.923 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
12-Mar-2024 16:04:33.923 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
12-Mar-2024 16:04:33.928 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1  11 Sep 2018]
12-Mar-2024 16:04:34.017 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
12-Mar-2024 16:04:34.054 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Mar-2024 16:04:34.069 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
12-Mar-2024 16:04:34.075 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Mar-2024 16:04:34.076 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1285 ms
12-Mar-2024 16:04:34.220 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
12-Mar-2024 16:04:34.221 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.8
12-Mar-2024 16:04:34.239 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/opt/tomcat/conf/Catalina/localhost/ROOT.xml]
12-Mar-2024 16:04:34.278 WARNING [main] org.apache.catalina.startup.HostConfig.deployDescriptor The path attribute with value [/ROOT] in deployment descriptor [/opt/tomcat/conf/Catalina/localhost/ROOT.xml] has been ignored
12-Mar-2024 16:04:34.288 WARNING [main] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase [/opt/tomcat/webapps/ROOT] inside the host appBase has been specified, and will be ignored
12-Mar-2024 16:04:40.648 WARNING [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = MISODB Property maxActive is not used in DBCP2, use maxTotal instead. maxTotal default value is 8. You have set value of "100" for "maxActive" property, which is being ignored.
12-Mar-2024 16:04:40.649 WARNING [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = MISODB Property removeAbandoned is not used in DBCP2, use one or both of removeAbandonedOnBorrow or removeAbandonedOnMaintenance instead. Both have default value set to false. You have set value of "true" for "removeAbandoned" property, which is being ignored.
12-Mar-2024 16:04:40.650 WARNING [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = MISODB Property maxWait is not used in DBCP2 , use maxWaitMillis instead. maxWaitMillis default value is -1. You have set value of "1000" for "maxWait" property, which is being ignored.
12-Mar-2024 16:04:41.424 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
12-Mar-2024 16:05:08.640 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/opt/tomcat/conf/Catalina/localhost/ROOT.xml] has finished in [34,400] ms
12-Mar-2024 16:05:08.646 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
12-Mar-2024 16:05:08.679 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
12-Mar-2024 16:05:08.698 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 34621 ms

**Comment by djcooke** [comment]
Hello,

I don't see any problems in your `catalina.out`, but hopefully one of the other logs gives some better clues. Can you check `miso_debug.log` (in the `logs` subdirectory of your MISO storage directory), and `localhost.<date>.log` (in your Tomcat `logs` directory) for any errors?

**Comment by LisaHagenau** [comment]
Hi, there is an error in the miso_debug.log:

> 2024-03-12 16:05:50 ERROR: Cannot process user login - cannot extract roles from database

**Comment by LisaHagenau** [comment]
I just checked the User table in the database again and there are no roles set for most logins, only for admin and notification and there seems to be a comma missing in the admin row. I can't login with either of these. 

> +--------+--------+-------+---------------------+----------+--------------+--------------------------+----------------------------------------------------------------------+-------------------------------------+
| userId | active | admin | fullName            | internal | loginName    | roles                    | password                                                             | email                               |
+--------+--------+-------+---------------------+----------+--------------+--------------------------+----------------------------------------------------------------------+-------------------------------------+
|      1 |      1 |     1 | admin               |        1 | admin        | ROLE_ADMINROLE_INTERNAL  | {SHA-1}d033e22ae348aeb5660fc2140aec35850c4da997                      | admin@admin                         |
|      2 |      1 |     1 | Notification Server |        1 | notification | ROLE_ADMIN,ROLE_INTERNAL | {SHA-1}d033e22ae348aeb5660fc2140aec35850c4da997                      | notification@notification           |

**Comment by djcooke** [comment]
> Cannot process user login - cannot extract roles from database

This error should only occur if `roles` is an empty string.

1. When you say "there are no roles set for most logins", is the `roles` database column null or blank? If blank, you might be able to fix the issue by changing them to null. MISO will use the admin and internal flags to determine roles in addition to the roles column itself, so this shouldn't cause any issues.
2. Does the same error message show up again in `miso_debug.log` when trying to log in as admin?

It looks to me like you should at least be able to log in as admin, so I think there might be something else going on here too. Can you confirm a couple more things?

3. Are you using JDBC (database) authentication, or Active Directory/LDAP?
4. Are you sure all database migrations were applied successfully during the upgrade? If you're not sure, you can check the `flyway_schema_history` table in your database. There should be a record with `version` 1400 and `success` 1 (`TRUE`)

**Comment by LisaHagenau** [comment]
> When you say "there are no roles set for most logins", is the roles database column null or blank? If blank, you might be able to fix the issue by changing them to null. MISO will use the admin and internal flags to determine roles in addition to the roles column itself, so this shouldn't cause any issues.

The column was blank for all users except admin and notifications. I set the roles to NULL, but the login still doesn't work. 

>    Does the same error message show up again in miso_debug.log when trying to log in as admin?

The error message stopped showing up, but I still can't login. I restarted tomcat, but the miso_debug.log only shows successfull startup, no login attempts.

> Are you using JDBC (database) authentication, or Active Directory/LDAP?

JDBC

> Are you sure all database migrations were applied successfully during the upgrade? If you're not sure, you can check the flyway_schema_history table in your database. There should be a record with version 1400 and success 1 (TRUE)

All the migrations were successfull. 

I also replaced the old securities.properties file in miso/storage with the one from the new version, but still no login possible.

**Comment by djcooke** [comment]
Strange that there's nothing more useful showing up in your logs... Maybe an issue on the front end? Can you open the developer console on your browser and see if any errors are showing up either when you load the login page, or when you try to log in?

Hopefully there's something there. If there's nothing helpful being logged, it's very difficult to troubleshoot such a large upgrade. Assuming you took a backup and are able to roll back, it would be much simpler if you could narrow down which version causes the issue. i.e. upgrade to 1.20.x and see if the issue occurs. If yes, roll back and try 1.15.x; if no, proceed to 1.30.x and go from there.

**Comment by LisaHagenau** [comment]
I looked at the browser console and found warnings regarding cookies:

> Cookie “JSESSIONID” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> Cookie “JSESSIONID” has been rejected because a non-HTTPS cookie can’t be set as “secure”.

I had previously deleted the cookie from my browser and it is not generated again when reloading the site. I found this code in $CATALINA_HOME/webapps/ROOT/WEB-INF/web.xml:
  
```
<session-config>
    <session-timeout>60</session-timeout>
    <cookie-config>
      <secure>true</secure>
      <http-only>true</http-only>
    </cookie-config>
  </session-config>
```

So maybe this error occurs because of a misconfigured cookie?

**Comment by djcooke** [comment]
Ah, glad you found the issue. MISO now requires SSL (HTTPS) with this setting. I would recommend setting up SSL rather than disabling it. Otherwise, all communication between the browser and server is transmitted in plain text, including passwords.

**Comment by LisaHagenau** [comment]
Thanks, I will look into setting up SSL. I also want to continue upgrading MISO to the latest version, but I have to check with our sysadmin first if I can update Java, MySQL and Ubuntu.
