### ISSUE TITLE
flyway cannot connect to db

### ISSUE THREAD

**Issue by clolalan7** [miso-lims/miso-lims#2923]
Hi, trying to get miso-lims v2.19 to work on my macbook pro. 
I get this error:
flyway-1  | WARNING: Connection error: Could not create connection to database server. Attempted reconnect 3 times. Giving up. (Caused by db: Name or service not known) Retrying in 1 sec...
And Mysql-8 is always "restarting"...

**Comment by djcooke** [comment]
Hello,

We're not experiencing this issue. Can you give some more information about your config and how you're starting it up?

**Comment by clolalan7** [comment]
I am trying to set up the demo right now... and following the instructions.
Tried again and noticed this after I start docker-compose -f demo.plain.yml up
WARN[0000] The "MISO_DB_ROOT_PASSWORD_FILE" variable is not set. Defaulting to a blank string. 
WARN[0000] /Users/clalance/miso-lims-compose/demo.plain.yml: `version` is obsolete 

flyway requires the root password... and it is not set? how can I fix this?
thanks
Claudia

**Comment by clolalan7** [comment]
just to all... the Mysql 8.0 container is in constant "restarting" state. 
I am on a mbp with intel core i7

**Comment by djcooke** [comment]
Are these the instructions you're following? https://miso-lims.readthedocs.io/projects/docs/en/v2.19.0/admin/compose-installation-guide/

The Quick Start section details bringing up the demo. `MISO_DB_ROOT_PASSWORD_FILE` is set in the line beginning with `export`. You do need to first create the file that you are specifying here

**Comment by clolalan7** [comment]
I was following the instructions on the github readme page, as I did for older version I tested. the creation of the root file is missing there. 
Just tested and it works.

**Comment by djcooke** [comment]
Glad that helped! I'll add some clarification to the instructions

**Comment by djcooke** [comment]
https://github.com/miso-lims/miso-lims/pull/2928

**Comment by Shellfishgene** [comment]
Maybe the quick manual on the main github page could also be fixed, this also took me a bit to figure out, too!
