### ISSUE TITLE
Moving from baremetal to docker

### ISSUE THREAD

**Issue by LisaHagenau** [miso-lims/miso-lims#2953]
Hello,

we are moving servers and I want to move our miso database to the docker installation on the new server. I have tried the demo version (both plain and detailed), but I am not sure if it is working correctly. 

- the docker-compose command doesn't work (command not found), I have to use docker compose (no dash)
- I can access the login page, but can only login with admin/admin when I also check the "stay logged in" box, otherwise it just stays on the login page. 
- if I click on anything in the left menu after logging in it just logs me out again

Is this expected behaviour? 
I am running Docker version 24.0.2, build cb74dfc and Docker Compose version v2.20.2 (installed following docker manual). 

Regarding the setup for production use, would you recommend I set up the docker installation to the same version we are currently running on baremetal (1.51.2, still on mysql 5.7 and java 11) and then upgrade or can I try to migrate to a newer version at the same time?

Thank you!

**Comment by djcooke** [comment]
Whether you need to use `docker-compose` or `docker compose` will depend on your Docker installation. Login should work regardless of whether you've checked "stay logged in," and you should not be logged out when clicking menu items. Please let us know what instructions you followed and what MISO version you were running to encounter this problem.

Here is our guide for migrating to MySQL 8.0, which includes recommendations on which MISO versions to install. https://miso-lims.readthedocs.io/projects/docs/en/latest/admin/mysql-8-upgrade/

**Comment by LisaHagenau** [comment]
I followed the instructions from the manual (https://miso-lims.readthedocs.io/projects/docs/en/latest/admin/compose-installation-guide/#quick-start). I have tried it now for versions 2.19.0, 2.13.0 and 2.4.0 by changing the MISO_TAG variable, but the error remains the same. 
Could it be the server, which doesn't have a lot of resources (1 core, 8 GB RAM, Ubuntu 22), even though our current miso server has the same configuration (running Ubuntu 18)? Everything works smoothly and a lot faster when I tried it on a local machine.

**Comment by djcooke** [comment]
More resources may be ideal for production with heavy use, but MISO should run fine with 1 CPU and 8GB RAM.

I'm not sure what would be causing you to be logged out as you describe. The first thing I'd suggest is to ensure that you're starting from a clean environment by pruning your docker containers and volumes. **Warning:** this will prune all Docker containers and volumes, not just the MISO ones. If you have other containers/volumes you wish to preserve, take a more selective approach.

```
# (stop all docker containers before running this)
docker container prune
docker volume prune
```

Try again after that. If you are getting the same error, please check the logs in the webapp container for errors. Check `/storage/miso/log/miso_debug.log` first, and then the files in `/usr/local/tomcat/logs/`

**Comment by LisaHagenau** [comment]
Okay, so I am getting an error in miso_debug.log 

> 2024-07-30 07:20:54 INFO: Checking MISO storage paths...
2024-07-30 07:20:54 INFO: Directory (/storage/miso) exists.
2024-07-30 07:20:54 INFO: Directory (/storage/miso/log) exists.
2024-07-30 07:20:54 INFO: Directory (/storage/miso/temp) exists.
2024-07-30 07:20:54 INFO: Directory (/storage/miso/files) exists.
2024-07-30 07:20:54 INFO: Directory (/storage/miso/files/submission) exists.
2024-07-30 07:20:54 INFO: All storage directories OK
2024-07-30 07:20:56 INFO: Initializing Servlet 'miso'
2024-07-30 07:20:56 INFO: Completed initialization in 182 ms
2024-07-30 07:21:11 WARN: SQL Error: 1054, SQLState: 42S22
2024-07-30 07:21:11 ERROR: Unknown column 'this_.identificationBarcode' in 'field list'

In the stdout of the docker compose command, the flyway migration appears to be successful:

> miso-lims-compose-flyway-1  | Migrating schema `lims` to version 1590 - auto main
miso-lims-compose-flyway-1  | Successfully applied 194 migrations to schema `lims` (execution time 01:55.187s)
miso-lims-compose-flyway-1  | Executing SQL callback: afterMigrate
miso-lims-compose-flyway-1 exited with code 0 

I think the problem with the login might be that I don't have physical access to the server so I can't access the webapp with http://localhost, instead I go to the IP-address of the server. 
I have tried running the demo on a local workstation (which I have physical access to). In that case, if I access http://localhost/ on the workstation, the login and the miso interface works, but if I try to access it from a different computer via the IP-adress, it gives me the same login problems I have with the other server. 

I also noticed a big difference in the time it took for both demos to start; for the virtual server it was around 2 minutes, while the workstation took 12 seconds. Is that just due to available resources?

Not sure what the problem even is now... I think I will go ahead and try to get a production setup with our current database on the workstation to figure out the procedure and then repeat the steps on the server.

**Comment by djcooke** [comment]
I don't think the `identificationBarcode` error is related. Given that it occurred just a few seconds after the webapp was initialized, it's likely that the Flyway migrations hadn't completed yet and this type of database error would be expected.

The biggest thing that will affect startup time is your database state, assuming you're counting the Flyway migration as part of startup time. If your database is already at the latest version, the Flyway migration will be very quick; otherwise, it will take more time to apply whichever migrations are necessary.

Are the login/logout issues always happening when logging in from the same workstation and browser? Can you try a different workstation or browser? Is it possible you have cookies disabled? That would prevent your browser from holding the login.

**Comment by LisaHagenau** [comment]
> Are the login/logout issues always happening when logging in from the same workstation and browser? Can you try a different workstation or browser? Is it possible you have cookies disabled? That would prevent your browser from holding the login.

I have tried it with different browsers (Firefox and Safari) on a Macbook and with Firefox on a Linux workstation. Cookies are enabled, but the problem persists.

**Comment by LisaHagenau** [comment]
Okay, configuring https solved the problem, I can now access miso from a different workstation. 

I was also able to build and run the MISO version we are currently running (1.51.2) with docker. Now I just need to transfer the actual database to the new server, but I am not sure how to do this.

**Comment by LisaHagenau** [comment]
Successfully moved the database to the new server. Everything running smoothly for now.
