### ISSUE TITLE
Issue: Create Run

### ISSUE THREAD

**Issue by alexiandra97** [miso-lims/miso-lims#2960]
I am not able to create a run.

I got this error message:

Oh snap!
This form seems to be invalid

Something has gone terribly wrong. Please report this to your MISO administrator.

**Comment by djcooke** [comment]
Hello,

Can you please provide some more information to help us troubleshoot?

1. What version of MISO are you running?
2. When exactly does this happen? Is it when you click Save on the Create Run page?
3. Please check `miso_debug.log` for any errors and paste them here. The log is located in `/storage/miso/log` by default, but may be somewhere else depending on your configuration
