### ISSUE TITLE
Can't log in from another machine

### ISSUE THREAD

**Issue by marchoeppner** [miso-lims/miso-lims#2961]
Hi,

so I have MISO running on a local machine, via docker compose (presumably the latest version of the image). Everything works as expected. 

When I try to access the Miso interface from another machine, same network, I get the login screen as expected, but after entering my credentials I am instantly thrown back to the login screen (the user is both "internal" and "admin"). 

When I check "stay logged in", I get into the main GUI - but as soon as I click on anything, I am back on the login screen. Likewise, the dashboard shows errors such as

```
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data
```

I have not configured SSL or anything like that (it's a private network, so didn't seem entirely necessary). 

Any idea what might be causing this?

Cheers
Marc

**Comment by marchoeppner** [comment]
Addendum - I ended up enabling ssl via a self-signed cert, and now it works.

**Comment by djcooke** [comment]
Hello,

As you've discovered, SSL is required to access MISO over any network. There is a note about this in the bare metal install guide, but I see that it's not mentioned in the Docker guide, so I will add a note there as well.
