### ISSUE TITLE
can't add subprojects 

### ISSUE THREAD

**Issue by LisaHagenau** [miso-lims/miso-lims#2979]
Hi,

after recently migrating to version 2.1.0, we realised that we weren't able to add subprojects anymore. 
On the "Create Subprojects" page, the dropdown menu for the Project column just contains empty values (see screenshot). 
Under Misc > Subprojects, all project names are shown as "Unknown", but they are working links, i.e. they lead to the correct project page when clicking on them. 

I can't figure out what the problem is. In the database, the Project table shows entries for all projects under projectId, title, name and code. 
<img width="1095" alt="241004_Miso-subproject" src="https://github.com/user-attachments/assets/907021e9-a49d-4ab2-a505-82db342f08c8">
<img width="1917" alt="Screenshot 2024-10-04 at 11 31 33" src="https://github.com/user-attachments/assets/6f14ac0e-711d-45b5-9054-1ddd9674d3d8">

I hope you can help,
Lisa

**Comment by djcooke** [comment]
This issue affects all versions of MISO from 2.1.0 to 2.23.1 (not yet officially released). We have a fix in for the next version. To work around this issue in the meantime, you have a few options:

1. Roll back an earlier version. Considering the previous official release requires a different version of MySQL, and you've already gone through that upgrade process, this is probably not ideal.
2. Create any subprojects you need via SQL. e.g.

    ```
    SET @userId = 1;
    INSERT INTO Subproject(projectId, alias, referenceGenomeId, priority, createdBy, updatedBy)
    VALUES (1, 'My Subproject', 3, FALSE, @userId, @userId);
    ```

3. Create a hotfix. To do this, you'd have to check out the MISO v2.1.0 code, make the same javascript changes included in [this commit](https://github.com/miso-lims/miso-lims/commit/f838bd96d6e2f6561d3ed8abc9893c766b928ad8), build the entire MISO project (`mvn clean install -o -DskipTests`), and then copy `miso-web/target/ROOT/scripts/header_script.*` (3 files) into `<tomcat>/webapps/ROOT/scripts/`, replacing the existing files there.
